### ISSUE TITLE
How to keep duplicate columns from showing in Time in Board Column view?

### ISSUE THREAD

**Issue by rrobertsor** [nbrown02/FlowViz#105]
### Discussed in https://github.com/nbrown02/FlowViz/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **rrobertsor** September 15, 2023</sup>
I'm struggling with being able to remove duplicate column references and each has some data tied to it. 

How do I get one visual on "waiting for other teams" vs 3 for a single work item?

Thanks!
~Rebecc
![image](https://github.com/nbrown02/FlowViz/assets/145143470/cd67bfc9-7472-4b6f-95dc-849a7699d063)
a</div>

**Comment by nbrown02** [comment]
Closing as now fixed
