### ISSUE TITLE
Number of Days Blocked Count incorrect

### ISSUE THREAD

**Issue by jenniferrosemitchell21** [nbrown02/FlowViz#106]
The number of days blocked according to FlowViz does not correspond to data in ADO. I think its basing the count off the Updated date rather than blocked date. This is happening across multiple templates, projects and work IDs.

![image](https://github.com/nbrown02/FlowViz/assets/134519976/c3e6432a-30a8-4a10-bbc2-d8f5874b51cd)
![image](https://github.com/nbrown02/FlowViz/assets/134519976/319b96d8-18a8-4c3e-bccb-bad79bcd7909)
![image](https://github.com/nbrown02/FlowViz/assets/134519976/7ddc013d-dd23-45ac-a6b3-d289c40e2a26)

**Comment by nbrown02** [comment]
@jenniferrosemitchell21 can you give this a retest for me?

**Comment by jenniferrosemitchell21** [comment]
@nbrown02 
This is what I'm getting : 

![image](https://github.com/nbrown02/FlowViz/assets/134519976/138ca7cb-ce26-455a-8030-69ded38944b7)

**Comment by nbrown02** [comment]
@jenniferrosemitchell21 can you try again?

**Comment by jenniferrosemitchell21** [comment]
@nbrown02 
Not had a chance to validate yet, but instantly looks better : 

![image](https://github.com/nbrown02/FlowViz/assets/134519976/3d21dba5-a967-4fb2-9e6f-204452842ea4)

**Comment by jenniferrosemitchell21** [comment]
@nbrown02 
Hi Nick, 
See screenshots. Not matching so far unfortunately 

![image](https://github.com/nbrown02/FlowViz/assets/134519976/59272fbf-fe97-4e10-956c-c08b0b362364)

![image](https://github.com/nbrown02/FlowViz/assets/134519976/2de80989-53e4-4232-a33c-bbc5369a7622)

![image](https://github.com/nbrown02/FlowViz/assets/134519976/08d4e794-14fe-478c-9a48-f156312786a0)

![image](https://github.com/nbrown02/FlowViz/assets/134519976/b1aed193-8ca5-4cd5-b4af-ef54c75a489c)

**Comment by nbrown02** [comment]
﻿How are those items being blocked? That looks like a custom field maybe?Sent from my iPhoneOn 26 Oct 2023, at 15:50, jenniferrosemitchell21 ***@***.***> wrote:﻿
@nbrown02
Hi Nick,
See screenshots. Not matching so far unfortunately

**Comment by jenniferrosemitchell21** [comment]
Hi Nick, Standard Blocked field utilised across all Projects 

![image](https://github.com/nbrown02/FlowViz/assets/134519976/698af0ee-f60a-4461-b9c2-e0e91a0bb456)

**Comment by nbrown02** [comment]
For thar particular work item, can you share screenshots of what the table view looks like in ADO? Specifically for the NumberOfBlockedDaysTotal column

**Comment by jenniferrosemitchell21** [comment]
@nbrown02 Hi Nick, I'm unsure which ADO table you mean?

**Comment by nbrown02** [comment]
Can you try the latest version @jenniferrosemitchell21 ?

**Comment by jenniferrosemitchell21** [comment]
Hi @nbrown02 , A few strange things going on. See table below, some are correct but majorly are incorrect. Checked this with 2 ADO Projects - can send over more data if you need it ?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/smitj266/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/smitj266/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


 ID | Blocked 'Yes' Date | FlowViz # of days blocked | Currently blocked
-- | -- | -- | --
101941 | 26-Oct | 9 | no
105659 | 23-Oct | 5 | no
107065 | 17-Nov | 3 | yes
107599 | 20-Oct | 4 | no



</body>

</html>

**Comment by nbrown02** [comment]
I think I'll just leave it - for the value it adds and the effort already spent on it (plus a lack of decent test data to work with) it's not going to be worth fixing...

**Comment by jenniferrosemitchell21** [comment]
@nbrown02 OK, understand. Will you be reverting the template to the prior version (where blocked was measured from Change Date?). I am working with another new Team now and would like to get them setup with this version of your dashboard (they dont yet have any power automate flows setup, so change date should suffice for them)

**Comment by nbrown02** [comment]
Yeah will do, finding the time might be a challenge though!Sent from my iPhoneOn 21 Nov 2023, at 14:15, jenniferrosemitchell21 ***@***.***> wrote:﻿
@nbrown02 OK, understand. Will you be reverting the template to the prior version (where blocked was measured from Change Date?). I am working with another new Team now and would like to get them setup with this version of your dashboard (they dont yet have any power automate flows setup, so change date should suffice for them)

**Comment by nbrown02** [comment]
Reverted back now @jenniferrosemitchell21 - closing this issue.

Won't fix due to test data limitations - documentation updated
