### ISSUE TITLE
Issue connecting FlowViz (Organization) to our ADO Organization

### ISSUE THREAD

**Issue by frickje** [nbrown02/FlowViz#107]
Our Project Collection Admin downloaded the FlowViz(Organization) file, attempted to connect, during the initial load, received an OLE DB or ODBC error.  Non Project Collection Admins are able to connect to a Project using the FlowViz(Project) file. 
Full error here:

"Data Refresh
Load was cancelled by an error in loading a previous table.
WorkItems Completed
Load was cancelled by an error in loading a previous table.
WorkItems In Progress
Load was cancelled by an error in loading a previous table.
WorkItems In Progress2
Load was cancelled by an error in loading a previous table.
Dates
Load was cancelled by an error in loading a previous table.
Areas
Load was cancelled by an error in loading a previous table.
Iterations
Load was cancelled by an error in loading a previous table.
WorkItems Bl0cked
Load was cancelled by an error in loading a previous table.
WorkItems WIP Age
OLE DB or ODBC error: [DataSource.Error] OData: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
WorkItems FlowEfficiency
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Projects
Load was cancelled by an error in loading a previous table.
WorkItemTypes
Load was cancelled by an error in loading a previous table.
Teams
Load was cancelled by an error in loading a previous table.
AgeSort
Load was cancelled by an error in loading a previous table.
Query parameters" 

**To Reproduce**
Error was thrown during initial load

**Desktop (please complete the following information):**
 - Windows 11
 - 64 bit

**Comment by nbrown02** [comment]
That looks like it was force closed due to data load, how many projects/work items are in your organisation?

**Comment by frickje** [comment]
We have 102 in our PRD instance (68 active projects and 34 that we consider in archived state).  That makes sense that its a data load issue, we successfully connected it to our Dev instance (12 projects).  Is there an option to work around our current issue? If there is an option to multi-select Projects during the load, that would be great!  Out of the 68 active projects, we may have approx 50 that would be interested in your metrics.
If not, and I could get our "archived" projects out of there; would 68 be too many?  
Really appreciate your help!!

**Comment by nbrown02** [comment]
It really depends more on the work items, I’m fairly confident 68 would be too many. Unfortunately there is no way to select multiple projects :(Sent from my iPhoneOn 2 Nov 2023, at 13:38, frickje ***@***.***> wrote:﻿
We have 102 in our PRD instance (68 active projects and 34 that we consider in archived state).  That makes sense that its a data load issue, we successfully connected it to our Dev instance (12 projects).  Is there an option to work around our current issue? If there is an option to multi-select Projects during the load, that would be great!  Out of the 68 active projects, we may have approx 50 that would be interested in your metrics.
If not, and I could get our "archived" projects out of there; would 68 be too many?
Really appreciate your help!!

**Comment by frickje** [comment]
Bummer to hear.  What are your thoughts on us trying to connect to our individual projects using the FlowViz (Project) file, then trying to combine them into one large dataset? Would we be wasting our time? Any other suggestions?

**Comment by nbrown02** [comment]
Closing issue as due to data volumes being loaded, workaround provided.

**Comment by frickje** [comment]
CONFIDENTIAL & RESTRICTED

Hi Nick,

Quick follow up on this. Can you give me a little guidance on how I would update a query?  For example, on the Iterations, I see the following (Transform Data, Applied Step - Source):

= OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/" & Project & "/_odata/v3.0-preview/Iterations?%20&$select=ProjectSK,IterationPath,IterationName,IterationSK,StartDate,EndDate,IterationLevel1,IterationLevel2,IterationLevel3,IterationLevel4", null, [Implementation="2.0"])

Am I placing the project names in place of the "Project" parameter?

Appreciate the guidance!
jessica

________________________________

**Comment by nbrown02** [comment]
You would need to do something like:

= OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/_odata/v3.0/Iterations?%20$filter=%20Project/ProjectName%20eq%20%27**PROJECTNAME**%27%20or%20Project/ProjectName%20eq%20%27**PROJECTNAME**%27%20&$select=ProjectSK,IterationPath,IterationName,IterationSK,StartDate,EndDate,IterationLevel1,IterationLevel2,IterationLevel3,IterationLevel4", null, [Implementation="2.0"])

Bold is where you'd need to enter project name, similarly you'd need to take the project parameter out of the query...

**Comment by frickje** [comment]
CONFIDENTIAL & RESTRICTED

Thank you SO much. I'll start working on the updates. I have two successful so far.
________________________________

**Comment by frickje** [comment]
CONFIDENTIAL & RESTRICTED

Hi Nick,

Are you able to help me with one more?  I have the other queries updated, but struggling with the "Teams".

Here is the original:

= OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/" & Project & "/_odata/v3.0-preview/BoardLocations?%20&$select=TeamSK,ColumnName&$expand=Team($select=TeamName)", null, [Implementation="2.0"])

I tried to update it to:
= OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/" & "/_odata/v3.0-preview/BoardLocations?$filter=%20Project/ProjectName%20eq%20%27Mobile%27%20or%20Project/ProjectName%20eq%20%27NavIP%27%20&$select=TeamSK,ColumnName&$expand=Team($select=TeamName)", null, [Implementation="2.0"])

but I get the following error:
[cid:fb3dfb75-c2ed-49bc-a23c-35de9ee9fb3b]

(I am not a developer, if you haven't guessed 🙂)

Thanks,
Jessica
________________________________

**Comment by nbrown02** [comment]
Hey Jessica,

So I don't think for that table you would be able to do it - Project isn't an available field for that table.
