### ISSUE TITLE
Error when trying to refresh data

### ISSUE THREAD

**Issue by orlando-noda** [nbrown02/FlowViz#113]
**Describe the bug**
Hi!
A few weeks ago, I've connected the FlowViz dashboard with my Azure backlog. I could load all data, play around with all dashboards (amazing work, btw). But now, when I try to refresh data, I got many lines of erros saying "Load was cancelled by an error in loading a previous table", and two other erros as you can see on screenshots bellow.

**To Reproduce**
1. Setup FlowViz connected to an ADO backlog;
2. Click on "Refresh" button, to update data;
3. Get many lines of errors and no data is updated

**Expected behavior**
I expect that the refresh works fine and the data is updated

**Screenshots**
![powerbi-error1](https://github.com/nbrown02/FlowViz/assets/5967047/971002ff-38b3-4685-a140-95381f4b4d67)
![powerbi-error2](https://github.com/nbrown02/FlowViz/assets/5967047/e717f0bd-4e1c-42ba-a284-d8848c38b7f6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Power BI Desktop
 - Version: 2.124.1052.0 64-bit 

**Additional context**
I've connected using a personal access token (I have checked and this token still valid)

**Comment by nbrown02** [comment]
Hi there,

Thanks for sharing. 

Is this a large ADO project? The error is one typically seen with a timeout due to a large dataset (I have several reports on a scheduled refresh not seeing any errors). 

The workaround would be to change those tables and their queries to be a shorter date range...

**Comment by orlando-noda** [comment]
Yes, it is a huge project. They have over 50 teams on this project.

I've tried to change one query, but with no success.

**Original query:** = OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/" & Project & "/_odata/v3.0-preview/WorkItemRevisions?" & "$apply=filter(" & "StateCategory ne 'Proposed'" & "and WorkItemType ne 'Issue'" & "and WorkItemType ne 'Task'" & "and WorkItemType ne 'Test Case'" & "and WorkItemType ne 'Test Plan'" & "and WorkItemType ne 'Shared Parameter'" & "and WorkItemType ne 'Shared Steps'" & "and WorkItemType ne 'Test Suite'" & "and WorkItemType ne 'Impediment'" & "and WorkItemType ne 'Epic'" & "and WorkItemType ne 'Feature'" & "and ChangedDate ge 2023-06-01T00:00:00Z" & ")", null, [Implementation="2.0", OmitValues=ODataOmitValues.Nulls, ODataVersion=4])

**New Query:** = OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/" & Project & "/_odata/v3.0-preview/WorkItemRevisions?" & "$apply=filter(" & "StateCategory ne 'Proposed'" & **"and Area Path eq 'Project\Systems\Opportunity to Cash'"** & "and WorkItemType ne 'Issue'" & "and WorkItemType ne 'Task'" & "and WorkItemType ne 'Test Case'" & "and WorkItemType ne 'Test Plan'" & "and WorkItemType ne 'Shared Parameter'" & "and WorkItemType ne 'Shared Steps'" & "and WorkItemType ne 'Test Suite'" & "and WorkItemType ne 'Impediment'" & "and WorkItemType ne 'Epic'" & "and WorkItemType ne 'Feature'" & "and ChangedDate ge 2023-06-01T00:00:00Z" & ")", null, [Implementation="2.0", OmitValues=ODataOmitValues.Nulls, ODataVersion=4])

When I tried to change this query, got the following error:
![error3](https://github.com/nbrown02/FlowViz/assets/5967047/8f401986-fb61-495b-a8b5-3b773c4cbf8b)

**ps:** I'm not a developer, so maybe a simple detail that I'm missing.

**Comment by nbrown02** [comment]
So there is a thread in discussions on area path filtering - https://github.com/nbrown02/FlowViz/discussions/33

I'd also try change the date range, as it is loading from June 1st (2023-06-01) it might make sense to start from say September (2023-09-01)

**Comment by orlando-noda** [comment]
Hi, @nbrown02 ! Just to let you know that this work around has worked to me.

Thank you for the support

**Comment by nbrown02** [comment]
Fantastic glad to hear it!On 10 Jan 2024, at 19:12, Orlando Noda ***@***.***> wrote:﻿
Hi, @nbrown02 ! Just to let you know that this work around has worked to me.
Thank you for the support

**Comment by jenniferrosemitchell21** [comment]
@orlando-noda Hi there, Would you mind sharing how you restricted your data? Which Query did you do this in? I've looked at the queries but none of them mirror your paste above.

**Comment by orlando-noda** [comment]
Hi, @jenniferrosemitchell21! I had to edit the query of every table and add a filter parameter to limit my query to a specific areaPath. Here is an example of a table called "WorkItems Bl0cked"

### Edited Query
= OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/" & Project & "/_odata/v3.0-preview/WorkItemRevisions?" & "$apply=filter(" & "StateCategory ne 'Proposed'" & **"and startswith(Area/AreaPath,'Systems\Opportunity\')" &** "and WorkItemType ne 'Issue'" & "and WorkItemType ne 'Task'" & "and WorkItemType ne 'Test Case'" & "and WorkItemType ne 'Test Plan'" & "and WorkItemType ne 'Shared Parameter'" & "and WorkItemType ne 'Shared Steps'" & "and WorkItemType ne 'Test Suite'" & "and WorkItemType ne 'Impediment'" & "and WorkItemType ne 'Epic'" & "and WorkItemType ne 'Feature'" & "and ChangedDate ge 2023-10-01T00:00:00Z" & ")", null, [Implementation="2.0", OmitValues=ODataOmitValues.Nulls, ODataVersion=4])
