### ISSUE TITLE
Tooltip showing 'blank' week commencing date for some weeks

### ISSUE THREAD

**Issue by jenniferrosemitchell21** [nbrown02/FlowViz#114]
Hi Nick, Just noticed that the tooltip for throughput. quality and sustainability graphs is missing the dates from the last few weeks. 

- This is your latest Dec 5th template version. 
- I have no filters applied
- I've checked the dates table and it runs to 2024 end
- I've checked the tooltip sheets and they seem fine

![image](https://github.com/nbrown02/Story-Point-Correlation/assets/134519976/4518cc68-7359-43fc-9920-a690b0a05105)

**Comment by nbrown02** [comment]
Sorry not seeing it on any reports my end - does it happen if you refresh?

![image](https://github.com/nbrown02/FlowViz/assets/29369962/ba823870-a580-48d0-8c62-abb73df4b606)

![image](https://github.com/nbrown02/FlowViz/assets/29369962/13741a62-7c29-45da-bd36-32a5f3422e78)

**Comment by jenniferrosemitchell21** [comment]
Hi Nick,
I've set the reports to automatically refresh on a daily basis, but have just refreshed it now and unfortunately still getting blanks. Weirdly the blanks seem to vary depending on the Team filter. Is there anything I can check on my end? 

![image](https://github.com/nbrown02/FlowViz/assets/134519976/cda374db-1e5f-4cf0-86be-efe7b9ae627e)

**Comment by nbrown02** [comment]
The only other thing to check would be making sure no relationships have
been created between tables incorrectly - I've just reviewed all the
reports I use currently and published new ones to the service and still not
seeing this issue on any of the reports :/

**Comment by jenniferrosemitchell21** [comment]
Hi Nick, I have 3 reports with no additional relationships and one were I have created 2 extra relationships in order to get a Work Item Type filter. For the 3 reports with no changes made, at the top level dates are there in the tooltip. But when filtering by Team the tooltip disappears. If there is anything else I can try, let me know. If there's nothing that can be done that's fine - please close the ticket and I thank you for your wonderful template! :D

**Comment by nbrown02** [comment]
Got to the bottom of this after going back through a few years' worth of templates. It seems over the years that one relationship has changed in its filtering, instead of being set to 'both' it should be 'single':

![image](https://github.com/nbrown02/FlowViz/assets/29369962/4d45c8da-d582-4292-93af-c2dcbb5ba273)

When changing this it fixes it for me

**Comment by jenniferrosemitchell21** [comment]
Hi Nick, Thank you very much indeed!! Really appreciate it. I will change that now.

**Comment by nbrown02** [comment]
Closing as now resolved :)
