### ISSUE TITLE
Unable to load data into Power Bi

### ISSUE THREAD

**Issue by Raymond278** [nbrown02/FlowViz#117]
**Describe the bug**
I just downloaded the template and inputted the information needed for it to pull the data into power bi. But as soon as I load it, it shows me this error.
<img width="817" alt="image" src="https://github.com/nbrown02/FlowViz/assets/68884697/2dad33d2-c85a-4835-a35f-47ba2bb1b146">

**To Reproduce**
Followed the steps provided in the Market place, and in Github

**Expected behavior**
What i expected to happen was that it was going to pull all the information across my organization and pull that data into Power Bi.

**Screenshots**
<img width="817" alt="image" src="https://github.com/nbrown02/FlowViz/assets/68884697/e823cc31-51b2-47e2-8a16-402975840e97">

**Desktop (please complete the following information):**
 - OS: [Window 11 OS Build 22621.2861]
 - Browser [Google Chrome]
 - Version [22H2]

**Comment by nbrown02** [comment]
Hi there,

Thanks for sharing - can you share your ADO org details and what you have
entered into the template please?

I assume you have set up the access token/org login to load data?

Kind regards,

Nick
