### ISSUE TITLE
Days Lost to being Blocked Graph - potential error

### ISSUE THREAD

**Issue by jenniferrosemitchell21** [nbrown02/FlowViz#118]
Hi Nick, I think I might have found an error with the Days Lost to being Blocked Graph. Below one example, do please let me know if you need more?

Data table shows cycle time as 6 vs Blocked graph shows cycle time as 13.

![image](https://github.com/nbrown02/FlowViz/assets/134519976/04facbeb-cce3-433b-872a-c71a04ae746b)
![image](https://github.com/nbrown02/FlowViz/assets/134519976/06989fa8-4afb-4436-b699-85b8d503ddd1)

Data table shows Number of Days blocked as 6, but it is 2. 

![image](https://github.com/nbrown02/FlowViz/assets/134519976/965ccd9c-3b18-4668-8e39-0ff1514e572b)

**Comment by nbrown02** [comment]
Fixed now :)

**Comment by jenniferrosemitchell21** [comment]
Thank you Nick! :) 
What did you do so I can check if I need to make any changes to the 'Resolved Toggle' template?

**Comment by nbrown02** [comment]
You just need to change the tooltips for cycle time to be max rather than
sum:

[image: image.png]
