### ISSUE TITLE
Visuals for Forecast uncertified

### ISSUE THREAD

**Issue by rmwilkins** [nbrown02/FlowViz#121]
**Describe the bug**
When running a published report, the visuals for the Forecast Tab using D3JSVisual cannot be displayed as the visual is uncertified.

**To Reproduce**
1. Publish the report/dashboard
2. Click on Forecast page
3. See error for the two visuals "Uncertified Visuals from AppSource......."

**Expected behavior**
The visuals display.

**Additional context**
Note that the visual in the PowerBI deskop works fine.  Its just when the report is published.

**Comment by nbrown02** [comment]
Hi there,

This isn’t an issue with the template. Unfortunately this is due to the settings within your Power BI Workspace which your admin controls - there is no fix for this other than these settings to change.

Thanks,

Nick
