### ISSUE TITLE
Forecasting tab not working in PowerBI Desktop Reporting Server

### ISSUE THREAD

**Issue by BerndVoegele** [nbrown02/FlowViz#122]
Forecasting tab is working in PowerBI Desktop but loading the template in PowerBI Desktop Reporing Server just blocks the complete application. 

**To Reproduce**
1. Open FlowViz template in PowerBI Desktop Reporting Server (not the normal PowerBI Desktop)
2. Click on 'Forecast' tab
3. PowerBI Desktop Reporting Server is blocked (CPU usage of 10% in the background but not returning after hours)

**Expected behavior**
Visual should also work for  PowerBI Desktop Reporting Server

**Desktop (please complete the following information):**
 - OS: Windows 10
 -  PowerBI Desktop Reporting Server (Version: 2.124.1960.0 64-bit (Januar 2024))

**Comment by nbrown02** [comment]
Hi there,

Unfortunately PowerBI Desktop Reporting Server isn't supported.

Thanks,

Nick
