### ISSUE TITLE
Failure to load Data

### ISSUE THREAD

**Issue by davidajacobus** [nbrown02/FlowViz#123]
Similar to what was written in this issue: https://github.com/nbrown02/FlowViz/issues/117 
Data seems to load in preview correctly, however it fails during the actual load. Tested each endpoint with the proper parameters that are passed during the query and independently in the browser they function correctly. 

The failure seems to change each time

WorkItems FlowEfficiency
OLE DB or ODBC error: [DataSource.Error] OData: Invalid JSON. Unexpected end of input reached while processing a JSON string value..

WorkItems WIP Age
OLE DB or ODBC error: [DataSource.Error] The remote server returned an error: (500) Internal Server Error. (Internal Server Error).

**Comment by davidajacobus** [comment]
I can privately, yes. 
Interestingly, after a 4th attempt it appears to have loaded the data. In parallel I was running some manual checks on the analytics endpoints. I don't see a logical reason to the success suddenly when no alterations were made. Is it possible it is timing out and throwing a bad error?

**Comment by nbrown02** [comment]
Possibly yes. If it's a large project or using the organisation template this is more likely to happen.

**Comment by davidajacobus** [comment]
I was using the project-based template as the Organizational one was failing nearly immediately. I did not dive in deeper on that. I noticed the preview data which is a sub-set seems to load fine. Please leave this item open for the time being. I would like to conduct a few further refreshes to see the success rate.
