### ISSUE TITLE
Info graphic on Forecast tab needs to be brought forward

### ISSUE THREAD

**Issue by tennvol** [nbrown02/FlowViz#127]
**Describe the bug**
When clicking the Info icon on the Forecast tab, the graphic is obscured by the other elements on the page.

**To Reproduce**
1. Open the report
2. Click on Forecast tab
3. Click on Info icon
4. Note bubbles are obscured by other elements on the report

**Expected behavior**
Info graphic is readable and not obscured by other elements.

**Screenshots**
<img width="1280" alt="Forecast-Info-Error" src="https://github.com/user-attachments/assets/f8b1eb50-0f2d-4565-8545-560b1ffbaa12">
<img width="1277" alt="Forecast-Info-Error-Layer-Order" src="https://github.com/user-attachments/assets/8a402a92-6db7-4d8e-a444-1a7f6aa60205">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 126.0.2592.102

**Comment by nbrown02** [comment]
Thanks! This should now be fixed :)
