### ISSUE TITLE
What version of Power Bi?

### ISSUE THREAD

**Issue by tliang1212** [nbrown02/FlowViz#13]
I have installed Power Bi (the version released in May 2019) on my computer. Your Power Bi template cannot be opened due to version compatibility. 

Installed Power Bi Product Version:
2.69.5467.1801 (19.05) (x64)

Error Message:
'..\FlowViz - Agile Template.pbit' is incompatible with your current version of Microsoft Power BI Desktop. Please install the latest version and try opening the document again.

**Comment by nbrown02** [comment]
The prerequisite comments in the description say to “make sure you have the latest version of Power BI desktop downloaded” - it’s a hyperlink too to link to where you can download it 🙂

**Comment by nbrown02** [comment]
Closing as not an issue with the template, will edit instructions on Azure DevOps marketplace so it's clearer :)
