### ISSUE TITLE
Query is blocked because "We cannot convert the value null to type Text."

### ISSUE THREAD

**Issue by wouter-rab** [nbrown02/FlowViz#132]
When trying to load data into the (project) template I get the message that a number of queries (amongst others 'workitems completed' & 'workitems in progress') are blocked due to the following error:

_We cannot convert the value null to type Text._

Any idea on how to fix this?

**Comment by nbrown02** [comment]
Sorry need some more info on your parameters you are entering. Similarly is it that all tables are failing to load?

**Comment by wouter-rab** [comment]
Thanks for the almost instant reply!

I have not changed anything. The only thing I did was download the template from the Azure Devops marketplace and then make the connection with our project.

The full error I get is this so it looks like all tables fail to load.

Load
2 queries are blocked by the following errors:
WorkItems Completed
We cannot convert the value null to type Text.
WorkItems In Progress
We cannot convert the value null to type Text.
WorkItems In Progress2
We cannot convert the value null to type Text.
Dates
We cannot convert the value null to type Text.
Areas
We cannot convert the value null to type Text.
Iterations
We cannot convert the value null to type Text.
WorkItems Bl0cked
We cannot convert the value null to type Text.
WorkItems WIP Age
We cannot convert the value null to type Text.
WorkItems WIPLimit
We cannot convert the value null to type Text.
WorkItems FlowEfficiency
We cannot convert the value null to type Text.
WorkItemTypes
We cannot convert the value null to type Text.
Teams
We cannot convert the value null to type Text.
Query parameters

**Comment by nbrown02** [comment]
What parameters are you entering?

**Comment by wouter-rab** [comment]
Sorry, I didn't really understand before. These are my settings:

Http/Https:
https

Analytics URL/Azure DevOps Server:
analytics.dev.azure.com

Organization:
raboweb

Project:
Tribe Business Lending

**Comment by nbrown02** [comment]
Thanks - can you also send the ADO project details?

**Comment by wouter-rab** [comment]
Sorry I don't understand you again. What do you mean by project details?

**Comment by nbrown02** [comment]
Your azure devops project details - this would be in your URL/address bar :)

**Comment by wouter-rab** [comment]
Our organization works with teams next to project. My own team has the following URL but I'd like PowerBI to show the data on project level.

https://dev.azure.com/raboweb/Tribe%20Business%20Lending/_backlogs/backlog/Team%20Artemis

Does this help?

**Comment by nbrown02** [comment]
Thanks - can you try access this URL in the Web Browser:

https://analytics.dev.azure.com/raboweb/Tribe%20Business%20Lending/_odata/v3.0-preview/WorkItems
?

**Comment by wouter-rab** [comment]
Yes I can, I tried that already based on another thread in this github.

**Comment by nbrown02** [comment]
Hmm that is odd. Can you clear the parameters and re-enter them?

**Comment by wouter-rab** [comment]
I tried and this time I added the % instead of spaces when entering the project details.

I get a similar but not the same error now:

Data Refresh
Load was cancelled by an error in loading a previous table.
WorkItems Completed
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
WorkItems In Progress
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Dates
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Areas
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
WorkItems Bl0cked
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
WorkItems In Progress2
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
WorkItems WIP Age
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Iterations
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
WorkItems FlowEfficiency
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
WorkItemTypes
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Teams
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
AgeSort
Load was cancelled by an error in loading a previous table.
WorkItems WIPLimit
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..

**Comment by nbrown02** [comment]
Very strange. The OLE DB or ODBC errors are likely due to a timeout - it is a large project?

In any case, I'd recommend going into Power Query (via 'Transform Data') and going through each 'Applied steps' till you find where the error occurs:

![image](https://github.com/user-attachments/assets/212a1681-918d-4ea0-94b6-92aabcee1735)

**Comment by wouter-rab** [comment]
It is a very large project. Any way that I can change the queries to zoom in on teamlevel? Maybe that would work.

**Comment by nbrown02** [comment]
Try this one https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project%20-%20Team%20filter).pbit

**Comment by wouter-rab** [comment]
You are amazing! I got it to work in two tries. It failed to do al queries at first but I found out that this is due to the spaces in our project and team name. When I replaced the parameters to include %20 instead of spaces it worked.

I guess that going on project level was too much to handle for the server or something.

**Comment by nbrown02** [comment]
Nice one! Yeah that definitely is the case when it does the OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E error - the null one is one I haven't seen before :/ 

I will close this issue as a workaround is available :)

**Comment by wouter-rab** [comment]
I think the null one might also have to do something with spaces in the project or team name in the parameters. I noticed that in some queries there is a filter step and that filter step results into empty tables when there are spaces involved. If a next step then references that table or a field in that table and tries to convert it into text or something an error might be thrown.
