### ISSUE TITLE
Something went wrong error when opening template

### ISSUE THREAD

**Issue by ChristopherMank** [nbrown02/FlowViz#133]
**Describe the bug**
Downloaded the latest version of Power BI (Aug 2024) and FlowViz(Project). When I open it in Power BI, I get this error.

**To Reproduce**
1. Download latest version of Power BI (Aug 2024 in this case).
2. Download the file [FlowViz (Project).pbit](https://github.com/nbrown02/FlowViz/blob/main/FlowViz%20(Project).pbit).
3. Open in Power BI.

**Expected behavior**
The error should not appear and the visuals should load.

**Screenshots**
![image](https://github.com/user-attachments/assets/e5879c2c-0317-4404-a318-46440f597661)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 127

**Additional context**
I still do try to enter in the prompts and click Load but the same message appears again and it throws other errors about queries not loading.

**Comment by nbrown02** [comment]
Hey Christopher - Thanks for reaching out. I am currently using this version:
![image](https://github.com/user-attachments/assets/79924072-d392-4a6b-a79b-026e9af1fce8)

And not seeing any issues.

How are you opening it? Is it open Power BI then the .PBIT, or just double clicking the .PBIT (or both) ?

Have you tried uninstalling/reinstalling Power BI (if that's possible/not locked down by your IT admin) ?

Not sure if it will fix it, but I have added a new process template - all I've done is change the date range that data is loaded from as this needed doing anyway...

**Comment by ChristopherMank** [comment]
Thank you! A reinstall of Power BI fixed it.
