### ISSUE TITLE
Incorrect Tooltip Color

### ISSUE THREAD

**Issue by ChristopherMank** [nbrown02/FlowViz#134]
**Describe the bug**
The flyout tooltip for the Stale Work and Daily WIP x Work Item Age uses the wrong colors when toggling between regular and dark mode.

**To Reproduce**
1. Go to the WIP tab.
2. Hover over any of the data points in either chart.
3. The color will be as shown in the screenshots.

**Expected behavior**
The background color in regular mode should be white, while it should be dark in dark mode.

**Screenshots**
![image](https://github.com/user-attachments/assets/25d14ac8-8758-48f5-85e7-bbb2d82ae9c2)

![image](https://github.com/user-attachments/assets/3c33cf0a-cbc5-47a0-bb1d-6915b1b0184f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 128

**Additional context**
None

**Comment by nbrown02** [comment]
Nice spot - i will get this sorted in a new version in the next couple days

**Comment by nbrown02** [comment]
Now fixed :)
