### ISSUE TITLE
Incorrect Plotting on Lead Time Scatter Plot

### ISSUE THREAD

**Issue by ChristopherMank** [nbrown02/FlowViz#135]
**Describe the bug**
The lead time scatter plot graph appears to not be plotting the data correctly. On the lead time scatter plot, there were two items completed on 8/6, one with a lead time of 17 days and another 13 days. Instead of plotting two dots with the correct lead times, it plotted only one dot and appears to have summed the lead time days at 30 and plotted that. Any work items that were completed on the same day appear to do the same thing.

![image](https://github.com/user-attachments/assets/f4542caa-45a5-4a3b-8b9d-2ff5e752225a)

However, the cycle time scatter plot appears to be correct. If we take those same work items from 8/6, the cycle time scatter plot correctly created two dots with the same date, but correct cycle time.

![image](https://github.com/user-attachments/assets/9196a332-410c-4ce9-a768-f20daf6ef1be)

**To Reproduce**
1. Browse to the Cycle Time tab
2. Review the Lead Time Scatter Plot chart
3. Review work items that were completed on the same date

**Expected behavior**
The chat should plot separate dots with the correct lead times when work items are completed on the same date.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 128

**Additional context**
None

**Comment by nbrown02** [comment]
Looks like it's set to sum when it shouldn't - will get this sorted in yhe next version!

**Comment by nbrown02** [comment]
Now fixed :)

**Comment by ChristopherMank** [comment]
Thank you!!
