### ISSUE TITLE
Retain Applied Filters when Toggling Dark Mode

### ISSUE THREAD

**Issue by ChristopherMank** [nbrown02/FlowViz#136]
**Is your feature request related to a problem? Please describe.**
Whenever you have filters applied (e.g. Team) and then toggle between Dark Mode, the chart will clear all the filters.

**Describe the solution you'd like**
It would be great if the charts could retain the applied filters when you toggle Dark Mode.

**Describe alternatives you've considered**
None

**Additional context**
This is not a huge issue, a nice to have really.

**Comment by nbrown02** [comment]
I don't think this is possible as it's essentially a whole different set of visuals. I'll take a look for the next version and double check but unlikely to be one i'll fix

**Comment by nbrown02** [comment]
Beyond my knowledge for how to do this! Feel free to fork and PR if you get it working but won't be looking to add this myself!
