### ISSUE TITLE
Add a Chart for Distribution

### ISSUE THREAD

**Issue by ChristopherMank** [nbrown02/FlowViz#137]
**Is your feature request related to a problem? Please describe.**
The charts in FlowViz are wonderful, and there are good correlations back to the flow metrics of the flow framework. The one I'd say is missing is distribution, showing the ratios/%s of the work item types completed over a span of time. It would be great to see this chart introduced to the template.

**Describe the solution you'd like**
A new chart showing distribution of work item types completed over a period of time.

**Describe alternatives you've considered**
You can kind of see this and calculate yourself using the Productivity chart.

**Additional context**
None

**Comment by nbrown02** [comment]
Years ago I did have the flow framework style charts in FlowViz but I removed them as I'm not really a fan of it. So won't be looking to add this.
