### ISSUE TITLE
On premise platform with custom team field

### ISSUE THREAD

**Issue by SSPresson** [nbrown02/FlowViz#14]
I've tried FlowVis a few times with no results closely following instructions.  I'm not sure but I think this may be the issue.

I have a on premises server instance 2019.1 with a custom team field replacing the use of the area path as the team organizer.  I know this is a common adaptation and supported in the ADO process config but does FlowVis allow for that and how do I configure for it?  Is it possible for me to edit the report to allow for that?

**Comment by nbrown02** [comment]
Hey Scott,

So you’re not using Azure DevOps services? I haven’t tried using / testing against on premise tbh. Would be good if we could discuss and I can try work through?

Cheers,

Nick

**Comment by nbrown02** [comment]
Closing as no response - will reopen if appropriate
