### ISSUE TITLE
Blocked items not showing on the dashboard with "Blocked" field

### ISSUE THREAD

**Issue by marcoslopez1** [nbrown02/FlowViz#140]
**Describe the bug**
The "Blocked" field that comes by default hidden for the work items has been enabled and selected as the way to tag work items that are blocked (we're not using the tags field). Unfortunately blocked items identified this way are not showing up in the blocked tab of the dashboard, but the ones identified with the field tags as "blocked" they do appear.

For the four charts of the Blockers tab of the dashboard I realized:
- Current Blocked Items chart: the ones being tagged with Tags and also with the Blocked field, they both appear here.
- The ones just tagged with the field "Blocked" don't show up on the Days Lost, Blocked Frequency or MTTU charts.

**To Reproduce**
1. Set the field "Blocked" as "Yes".
2. Once the work item has no longer a blocker, set the field "Blocked" as "No".
3. Continue working on the work item until it reaches the "Closed" state.
4. Refresh the data and check the blocked tab of the dashboard.

**Expected behavior**
Blocked items using the "Blocked" field as "yes" and cleared to "no" at some point in the process, should also appear in the dashboard, not only the ones that use the Tags.

**Screenshots**
Here an example:
1) The work item is set as a blocked item with the "Blocked" field:
![image](https://github.com/user-attachments/assets/0bf75ff5-947e-4e2c-aefd-60c0974a95f2)

2) One day later the work item is unblocked and the field "Blocked" is set as "No":
![image](https://github.com/user-attachments/assets/2a069e33-ac70-4e93-ab75-030296d6f2bd)

**Additional context**
Same behavior described as in this other ticket, but unfortunately still getting the same problem as the user described on the ticket: https://github.com/nbrown02/FlowViz/issues/21

**Comment by nbrown02** [comment]
Thanks Marcos - let me look into this tonight and get back to you!

**Comment by marcoslopez1** [comment]
Thanks for the quick response Nick, I appreciate it!

Sure, let me capture that info here:

- The process template that I'm using is Agile (hope using the Scrum one is not the only way to get it, otherwise I got my answer already haha)
![image](https://github.com/user-attachments/assets/9c933506-610a-48a8-9372-4065606f2d54)

- And the field is the standard one, I selected it from the list of available fields:
![image](https://github.com/user-attachments/assets/5d302297-7a7b-4461-8fd3-ed5fcdcb8b92)
![image](https://github.com/user-attachments/assets/82c88799-f581-4cfb-953a-316f8d7f4906)

This is how an user can see it to report a blocker:
![image](https://github.com/user-attachments/assets/3404f281-e156-4600-9a31-494976b9498e)


Just a side note, we use the "blocked" field instead of the tags because we do have a column in our boards to report blocked issues. And since the only way to tag them is either using tags or this field, we decided to create a rule that is automatically defining the field as "yes" when it is moved into that blocked column (aka state) and it's moving it back to "no" once the work item is moved into another different column. Therefore, it is the system rule who is actually changing the value of the field automatically (I've also try to change it manually myself and still the same result).
![image](https://github.com/user-attachments/assets/9d4e1861-8148-4fe1-ae92-86358ffe18ce)

Let me know if you'd like to know more info or to test something on my end.

**Comment by nbrown02** [comment]
So replicating that setup I still see the same:

![image](https://github.com/user-attachments/assets/57946a94-77b5-4db3-8042-96a093325885)

![image](https://github.com/user-attachments/assets/56afb0a8-6f9a-4ff3-870e-e5a36a65b5de)

![image](https://github.com/user-attachments/assets/ede4824c-d461-46c1-8fc2-2b1e8adfaee8)

![image](https://github.com/user-attachments/assets/248a76b1-8f07-43dc-a562-f945f346eeb3)

Can you share the work item form for User Story and your states?

**Comment by marcoslopez1** [comment]
Sure, here it is the user story form (we do use the same field on bugs as well):

![image](https://github.com/user-attachments/assets/5eb6f9ae-2603-413d-9ef0-f5ab7ceee16a)

And these are the states we're using:

![image](https://github.com/user-attachments/assets/e493072a-26db-404d-9586-f9c3911275fe)

**Comment by nbrown02** [comment]
Sorry - can you show me the states in the process template. I need to mimic as close to your setup as possible...

**Comment by marcoslopez1** [comment]
Sure! Here we go:

![image](https://github.com/user-attachments/assets/45e7c443-ab67-4281-a072-104f9e5185d6)

**Comment by nbrown02** [comment]
Ok so part of the issue I can already see is the states and state categories isn't setup correctly. You shouldn't have a process template that goes out of state categories once work starts. It's going Proposed -> In Progress -> Proposed which isn't how ADO should be setup (and probably why the data is not working).

**Comment by marcoslopez1** [comment]
Thanks for pointing that out. I created a "blocked" state under the "In Progress" state category and kept the same configuration as before. Now the issues are showing up on the charts when using the default field "blocked" as well.

![image](https://github.com/user-attachments/assets/8f611001-6e1c-43a0-8263-d6f4c78fcbe5)
![image](https://github.com/user-attachments/assets/47c5895d-c5bc-4a89-a8ce-d90fefbe8a46)

In the MTTU chart I still see a 0 though, but I think that makes sense since I tested all this in less than an hour. I expect longer average blocked times to be reflected on the chart as soon as I start working with real data.

![image](https://github.com/user-attachments/assets/cb35f745-0338-4fdb-bc3b-02e9b60f4c27)

Thanks a lot for you time and support Nick!

**Comment by nbrown02** [comment]
Yeah that will be the case with just dummy data to check it works - phew! glad we got there in the end! If you have the time, don't forget to [leave a review on the ADO marketplace](https://marketplace.visualstudio.com/items?itemName=agile-extensions.flowviz) :)
