### ISSUE TITLE
Question with Blocker Frequency

### ISSUE THREAD

**Issue by ChristopherMank** [nbrown02/FlowViz#148]
The Blocker Frequency chart is a bit confusing. The PBI report states that it's showing how many items each day were blocked. Given this, I expected it to show a total of blocked items for each day (which is what I'd like to see). However, according to the wiki and the current chart behavior, the chart counts any time an issue is identified as ‘blocked’ each day. It looks like it's counting an item blocked on this chart only if it was marked blocked on that given day, not a total graph of blocked items for that day. So, if work items 12345 was blocked for a week, it will only show on this chart once, the first day it was blocked.

Is this behavior expected and what the graph is intended to show? If so, perhaps the verbiage/wiki could be updated to reflect that.

**Comment by nbrown02** [comment]
Hi there,

Yes that is correct. It shows frequency of occurrence rather than a running count. I can update the wording to reflect it better - what wording would make sense to you so that it's clearer?

**Comment by ChristopherMank** [comment]
Sounds great, thanks! Yes, I can see how challenging that is while trying to keep the verbiage short and concise. Perhaps this?

"How many items were updated to blocked on each day?"

**Comment by nbrown02** [comment]
I don't think that's really any different than now? 

I'd probably say it's better to change your own local version to reflect the wording you want rather than me changing the template (happy to provide guidance on how to do this if needed).

If more users have the same issue then I'd consider changing it but this is the first time it's been mentioned :)

**Comment by ChristopherMank** [comment]
Sounds good and fair enough. I felt that having the wording "updated to blocked" more accurately captures the behavior versus stating they were blocked (being in a state of blocked). But that sounds good. Appreciate your prompt responses!
