### ISSUE TITLE
Unable to Connect FlowViz to my organization or Project 

### ISSUE THREAD

**Issue by pooja2289** [nbrown02/FlowViz#15]
Hi Team - I am a newbie to Azure Devops world and I was trying to integrate FlowViz with my current organization/Project, however even after multiple attempts I am receiving the attached error. Also, It did not let me sign in using my Devops email. Request someone to please look at this and help me set this up. 

Thank you in advance! 
![FlowViz Error](https://user-images.githubusercontent.com/22241401/90153252-bd3c6800-dd56-11ea-9d24-912c859e6cb0.JPG)

**Comment by nbrown02** [comment]
Hey Pooja - noticed you closed this, did you manage to fix it?

**Comment by pooja2289** [comment]
> Hey Pooja - noticed you closed this, did you manage to fix it?

Hi, yes I managed to fix this. Thanks a lot for getting back to me, appreciate it. Look forward to use this.

**Comment by nbrown02** [comment]
Awesome great to hear, any questions please reach out 👍
