### ISSUE TITLE
Not compatible with newest PowerBI Desktop (2.84.701.0)

### ISSUE THREAD

**Issue by pandew** [nbrown02/FlowViz#16]
Version: 2.84.701.0 64-bit (August 2020) gives an error loading the FlowViz - Agile Template.  

**To Reproduce**
Open template FlowViz - Agile Template.pbit
add 
https://analytics.dev.azure.com/DocuShareHP/Desktop/_odata/v3.0-preview

click [load], get the below failures
Areas
Loading blocked by failures with other queries.
WorkItems Completed
The column 'ResolvedReason' of the table wasn't found.
Dates
Loading blocked by failures with other queries.
WorkItems In Progress WIP
The column 'ResolvedReason' of the table wasn't found.
Number of remaining items
Loading blocked by failures with other queries.
WorkItems (Count of InProgress)
The column 'ResolvedReason' of the table wasn't found.
Number of weeks to forecast
Loading blocked by failures with other queries.
Data Refresh
Loading blocked by failures with other queries.

click [ok]

Error: report has not been upgraded... 

PowerBI is then locked, with no way to shut it down except in Task Manager

**Expected behavior**
Update data model to match 

**Screenshots**
screen shot here:
![image](https://user-images.githubusercontent.com/39915315/90338295-b318a480-dfb6-11ea-8b00-2d5d0f2a6c40.png)

**Comment by nbrown02** [comment]
Thanks @pandew - Should be an easy one to fix, will take a look tomorrow and reply to this once a new version is available

**Comment by nbrown02** [comment]
@pandew can you retest this for me? Should now be fixed thanks 👍

**Comment by pandew** [comment]
Much better.  

I get into PowerBI now but get errors with the missing columns.  The column 'Risk' of the table wasn't found.  I got that error for all the workitem tables. 

Is that just my project or still part of the bug?

**Comment by nbrown02** [comment]
Hmm it’s odd because in all my projects with the Agile template, this loads fine. Ok let me take that column out too and see what happens (will ping when a new version available)

**Comment by nbrown02** [comment]
@pandew can you retry now?

**Comment by pandew** [comment]
I got another error about "StackRank", but I think I can work it from here. Thanks for your quick response!

**Comment by nbrown02** [comment]
Ahh it’s so weird - first time I’ve had this!

I’ll update the guidance for how to remove columns that throw up this error - thanks for your feedback/patience and please let me know if you have any thoughts on improvements 👍🏼
