### ISSUE TITLE
Forecast using effort instead of number of items

### ISSUE THREAD

**Issue by sean-burner** [nbrown02/FlowViz#17]
First, I want to thank you for all the work you've done for this project. It's so helpful for our team.

I was wondering if it is possible or even makes sense to forecast using effort rather than number of items? We have differently sized items in our backlog (user stories 1-20 story points). Can the forecasting charts be adjusted to use this number instead?

**Comment by nbrown02** [comment]
Hey Sean,

Thanks for reaching out and the kind feedback. I'll take a look into if we can add effort. 

Generally I would advise count, unless there is good correlation with your "effort" - i.e. 1's are pretty similar etc. - quite often teams are not very good at estimating (not their fault) and you'll find huge variances in what "1" effort items take.

If you forecast, then always use a consistent input data (i.e. don't input velocity and expect an output of count of stories!). I always say compare the two forecasts and see there difference :)

**Comment by nbrown02** [comment]
@sean-burner just following back up on this. Unfortunately there's no way to do this without changing the code in the d3 visual which would mean how it works currently would be impacted 😕

**Comment by nbrown02** [comment]
Closing as not a feature I'll be looking to add until D3 visual in Power BI becomes easier to edit code

**Comment by sean-burner** [comment]
Nick,

I am so sorry for not responding sooner. Thank you for the quick response- I was not actually expecting one at all, so it was a pleasant surprise!

I understand not being able to add the effort. I appreciate you looking in to this.

I have made some modifications to your template to suit our team needs and the response from my team has been incredible! I’ve invested a lot of time in the past trying to make insightful PowerBI reports with very limited success. I wish I would have found your template sooner. It’s amazing. Please keep up the good work!

Sean Burner | PSM
[DVC_logo_sign_text_side_line]

304-376-6699  | sean.burner@dataview.com<mailto:sean.burner@dataview.com> | www.dataview.com<http://www.dataview.com/>
No buzz words – just solutions that work!

Confidentiality note:  The above email contains information that is confidential and/or privileged. The information is for the use of the individual or entity originally intended. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this information is prohibited.

**Comment by nbrown02** [comment]
Hey Sean,

Thanks! That's great to hear, exactly the reason why it was built!

Could you leave a review on the Marketplace if possible? All helps in
gaining visibility :D

Cheers,

Nick

**Comment by sean-burner** [comment]
Absolutely! Thanks again

Sean Burner | PSM
[DVC_logo_sign_text_side_line]

304-376-6699  | sean.burner@dataview.com<mailto:sean.burner@dataview.com> | www.dataview.com<http://www.dataview.com/>
No buzz words – just solutions that work!

Confidentiality note:  The above email contains information that is confidential and/or privileged. The information is for the use of the individual or entity originally intended. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this information is prohibited.
