### ISSUE TITLE
Cannot Access DevOps from PowerBI file

### ISSUE THREAD

**Issue by 37threeseven** [nbrown02/FlowViz#18]
Hi there,

Hope you are doing well.  

I was just wondering if you can help with the following issue I'm having.  I'm new to both Power BI and DevOps and I'm trying to get FlowViz up and running which looks amazing and will help us tremendously.

I'm opening the files that I downloaded (https://marketplace.visualstudio.com/items?itemName=agile-extensions.flowviz&ssr=false#overview) and it asks for my login details.  When trying to log in with my Organisational Account, I get the following:

The WWW-Authenticate header doesn't contain a valid authorization URI. Header value: 'Basic realm="https://xxxxxxxxxxx.app.analytics.visualstudio.com/",Bearer,TFS-Federated'.

However when I copy and paste the URL (https://analytics.dev.azure.com/company/project/_odata/v3.0/WorkItems (or Area or Date etc) in a browser, I get results.

I have also tried logging in with a Personal Access Token which does not work, BUT it does work when I create an odata query from Power BI.

I have installed the latest and greatest version of Power BI.

Is there something that needs to be set at the Azure DevOps level?

Your help will be much appreciated or if you could point me in the right direction that would be great.

**Comment by nbrown02** [comment]
Hey there,

Thanks for reaching out - this is a very odd message and the first time I
have ever seen something like this :/

Can I check which template file you are using (or have you tried with all
of them) ? As well as that can you double check spelling etc.?

Without screenshots it's a bit tricky - anyway you could email separately
screenshots/screen record?

Thanks,

Nick

**Comment by 37threeseven** [comment]
Hi Nick,

Thank you for getting back to me.
I have tried all 3 the template files and am getting the same issue.  I have also double checked that the spelling is correct and have someone else test as well.

I will email you some screenshots.

Thank you again.

JP

**Comment by nbrown02** [comment]
I managed to replicate this (or as best as I can do) earlier today. Are you signed in to Power BI Desktop? And if so is that email the same address as the Azure DevOps collection you are trying to load data from?

**Comment by nbrown02** [comment]
Signed out of all accounts and cleared cache, still getting this error. Logged an issue with Azure DevOps team...

**Comment by nbrown02** [comment]
@37threeseven please see this thread - https://developercommunity.visualstudio.com/content/problem/1266164/odata-authentication-issue.html explaining the issue/fix...nothing I can do from a template side :)
