### ISSUE TITLE
Feature Request - Provide a forecast in days and dates

### ISSUE THREAD

**Issue by wertzui** [nbrown02/FlowViz#19]
At the moment the forecast will always output weeks.
in addition it would be nice to also have days and dates so I don't have to calculate dates from from weeks.
And especially for small projects days would be nice.

**Comment by nbrown02** [comment]
The previous versions of FlowViz provided it in number of days and the feedback was it was too difficult to work out 😁 
I put weeks in as a happy medium as date was quite tricky to do...I'll see if date could be done and get back to you...

**Comment by nbrown02** [comment]
After investigation, I won't be looking to implement this due to the effort needed/value added, apologies.
