### ISSUE TITLE
Feature Request - Inputs for forecast: should be able to base it on a query / epic / feature

### ISSUE THREAD

**Issue by wertzui** [nbrown02/FlowViz#20]
At the moment the input is based on a date range, project, team and area.
Also the "Number of items to forecast" is based on a number.

It would be helpful if one / both of these could be based on a query, an epic or a feature.

Let's say, I have a side-project under Feature X which I know will be handled by developers A, B and C.
Then I would create a query which would just return work items, done by A, B and C and use a feature to provide the number of items.

In addition matching of items by Tag would also be nice:
If i have tagged my items with something like "UI", "API", "Database" and the new feature needs 1 item "UI", "API", 2 items "Database" and 1 item "Bug", the simulation could be based on these tags, so the simulation for the "UI" and "API" item would run on the past items with the same tags. As there is no "Bug" tag in the historic data, the simulation for this item would run on all past items.

**Comment by nbrown02** [comment]
Thanks for your feedback, I think I understand this one...

1) Re. forecast by Epic/Feature - so are you saying you'd like the ability to have a slicer for Epic/Feature which could then dynamically change the 'Current Backlog Size' number? Something like this:

![image](https://user-images.githubusercontent.com/29369962/101368283-ddaca700-389e-11eb-883d-8dbcb848e0ba.png)

2) Re. Tags - I can add TagNames into the CompletedItems dataset, but it would be up to users to manually add this to the charts as a filter, I'd be reluctant to add it as a slicer as it would clutter the page.

Thoughts?

**Comment by wertzui** [comment]
1. Yes
1.1 Also based on a query, not just an epic or a feature

2. No ;)
Lets say, my historic data includes the following (5 stories in total, example shamelessly taken from https://paper.dropbox.com/doc/Application-Kata-Software-Forecasting-bYEyp2HjiCgWbyaRIVlmQ)
Days needed to complete; Tags 
3; reporting
4; ui
10; persistence,bugfix
6; reporting,ui
2; bugfix

Now the items under the selected feature are the following (11 stories in total):
Number of items * Tags
2 * ui
1 * reporting, ui
3 * bugfix, ui
5 * database

For the simulation of the two ui stories, the randomly picked duration would either be 4 or 6.
For the simulation of the 1 reporting, ui story, the randomly picked duration would be 6
For the simulation of the 3 bugfix, ui stories, the randomly picked duration would be 4, 10, 6 or 2 (fallback, because no story with both tags exist)
For the simulation of the 5 database stories, the randomly picked duration would be 3, 4, 10, 6, 2 (fallback, because no story with the database story exists)

So the input data is not filtered by tags, but rather each story under an epic / feature / query would individually be looked at and matched to existing stories by tags.

**Comment by nbrown02** [comment]
Ah ok - so for the effort needed/time available I wouldn't be looking to implement that...although I can understand why it might be needed (feel free to fork if you want to take a stab at it!).

Will investigate what can be done with Epic/Feature - there is no way to merge queries setup by users with this dataset (if you open in Power BI via Azure DevOps it loads as its own .pbit template file)

**Comment by nbrown02** [comment]
Just about to deploy new versions that will allow filtering of 'Current Backlog Size' by a Parent work item...

![image](https://user-images.githubusercontent.com/29369962/101485676-6422c080-3953-11eb-9791-00e2e2df6a8e.png)

**Comment by nbrown02** [comment]
Added this feature in latest version for all templates 👍
