### ISSUE TITLE
Blocked items in scrum template do not show on Blockers tab

### ISSUE THREAD

**Issue by kcaswick** [nbrown02/FlowViz#21]
**Describe the bug**
The default scrum template includes a field "Blocked", which is "Yes" or "No". Items flagged with this do not show in the count of blocked work.

**To Reproduce**
1. In a project in the standard scrum template
2. Mark an item as blocked
3. Run FlowViz
4. Go to Blockers tab
5. Work item does not appear

**Expected behavior**
Work items marked as blocked using the standard field are counted in statistics. Not just ones marked with a Block tag.

**Comment by nbrown02** [comment]
Hi there,

Thanks for the feedback. I think if you check the default scrum template, blocked is not a field on the work item form:

![image](https://user-images.githubusercontent.com/29369962/106202850-6c101b80-61b2-11eb-8630-3dadd07812b2.png)

Is that the same on your end? Are you using an inherited process and making the blocked field 'visible' on the work item form?

I'd have to investigate if this is possible...it adds additional complexity in how blocked work is tracked :)

**Comment by kcaswick** [comment]
Hi Nick,

I guess the Blocked field is only tracked on tasks, not PBI. There is also an entire work item called an Impediment, which can be open or closed, but I'm not familiar with how that is used yet, so I'm not sure if it is the same as a blocker.

This company is not using an inherited process yet, we've only set it up recently and customization is still in our future. I believe it would say inherited at the top of this screen if we were.

[cid:image001.png@01D6F5A4.383075F0]



Kevin Caswick
Application Developer
Kevin.Caswick@miron-construction.com

Miron Construction Co., Inc.
PH 920.969.7374 | FX 920.969.7393
1471 McMahon Drive | Neenah, WI 54956
MIRON-CONSTRUCTION.COM
Miron Construction Co., Inc. is proud to be an Equal Opportunity / Affirmative Action Employer. We welcome and encourage ALL qualified applicants to apply for our open career opportunities. This email and attachment(s) may contain privileged and confidential information and are intended for the addressee(s) only. If you have received this email in error, please notify the sender immediately and delete the message. Any other use, printing, copying, forwarding or retention of this email, is strictly prohibited.

**Comment by nbrown02** [comment]
Hey Kevin,

Ah ok, gotcha :)
I was wondering if you had a setup like this:

![image](https://user-images.githubusercontent.com/29369962/106257998-32bcc780-6215-11eb-8d65-32a1b9b6c81d.png)

Blocked is a field you can add to any work item form, as it is already present in the DB (as like you say it's used in Tasks).

It's a little bit tricky (but not impossible) for me to tweak the Blockers page so we can account for this as a way work gets marked as 'blocked'. However I want to check if you guys actually do it this way first? Pointless building it otherwise :D 

Unfortunately no way I can calculate if tasks within a story are blocked and the time lost there, sorry about that...

**Comment by kcaswick** [comment]
Hi Nick,

No, we do not use it that way at this time. Given the small number of tasks we've marked as blocked yet, maybe it makes more sense for us to switch from using the standard field that came with the process template to a "Block" tag on the PBI.

Thanks,
Kevin


Kevin Caswick
Application Developer
Kevin.Caswick@miron-construction.com

Miron Construction Co., Inc.
PH 920.969.7374 | FX 920.969.7393
1471 McMahon Drive | Neenah, WI 54956
MIRON-CONSTRUCTION.COM
Miron Construction Co., Inc. is proud to be an Equal Opportunity / Affirmative Action Employer. We welcome and encourage ALL qualified applicants to apply for our open career opportunities. This email and attachment(s) may contain privileged and confidential information and are intended for the addressee(s) only. If you have received this email in error, please notify the sender immediately and delete the message. Any other use, printing, copying, forwarding or retention of this email, is strictly prohibited.

**Comment by nbrown02** [comment]
Ok cool - one less thing for me to build is always handy!

**Comment by nbrown02** [comment]
@kcaswick - if you do use the blocked field (like in my earlier question), this is now supported in the latest version :)
