### ISSUE TITLE
Page filter on Blockers tab different between dark mode and regular copy

### ISSUE THREAD

**Issue by kcaswick** [nbrown02/FlowViz#22]
**Describe the bug**
The page filter on the Blockers page for WorkItemType is different between the dark mode template and the light mode & organizational templates.

**To Reproduce**
Open each template, look at the filters on the blockers page.

**Expected behavior**
Filters are all the same, and work regardless of whether you are using scrum or agile process template.

**Screenshots**
![image](https://user-images.githubusercontent.com/24442686/106298793-f8095e00-6219-11eb-93d8-1b7e826a88d8.png)
vs
![image](https://user-images.githubusercontent.com/24442686/106298845-0c4d5b00-621a-11eb-8f85-6ed1802e1064.png)

**Additional context**
The Blockers page filter appears to be different from the other pages of the light mode template as well. I like the filter by exclusion better, as otherwise Product Backlog Items are excluded.

**Comment by nbrown02** [comment]
Good spot! I'll check all of these and make sure they're consistent 👍

**Comment by nbrown02** [comment]
Fixed now 👍
