### ISSUE TITLE
How to allow FlowViz in my organization

### ISSUE THREAD

**Issue by josbar3131** [nbrown02/FlowViz#32]
The visuals built using D3JSVisual  don't work if we publish the pbix on our power BI service because these are not certified.
The way to allow uncertified visuals on an organization is by setting AppSource visuals or .pbiviz files as organization visuals, but on this case it is not possible to do so, because we don't have the .pbivis.

Can you help me?

**Comment by nbrown02** [comment]
@josbar3131 sorry no, this isn't something I can help with and outside the scope of FlowViz to address.
