### ISSUE TITLE
404 Error Trying to Load Data

### ISSUE THREAD

**Issue by djligda** [nbrown02/FlowViz#35]
Hi,

I have double checked everything, including the documentation, but continue to get an error when trying to Load data from Azure DevOps.  Any suggestions on something I may have overlooked?

![image](https://user-images.githubusercontent.com/87544244/125993781-b99ecbae-0ffe-46e6-8024-a9128dbd9e5d.png)

Thanks.

David

**Comment by nbrown02** [comment]
Hmm thanks for sharing. Not something I'm seeing when testing. Have you tried to query just using the web URL? The error message is normally common if the parameters are incorrect or the project name has changed...

If it's easier, feel free to email nicolas.brown@outlook.com :)

**Comment by nbrown02** [comment]
Closed as resolved with user :)

**Comment by iandavies123** [comment]
I'm getting the same error, will try via the web now but wondered what the solution was previously? @nbrown02 @djligda
