### ISSUE TITLE
Current backlog size on Forecast tab not correct

### ISSUE THREAD

**Issue by jmezach** [nbrown02/FlowViz#36]
**Describe the bug**
I've noticed that the Current Backlog Size (including WIP) counter in the top right of the Forecast tab isn't correct. I've had a look at the query and it looks this is caused by the fact that it performs a Count on the WorkItemID on the WorkItems In Progress2 table which includes the same work item multiple times, once for each state it has had (I think). By changing the visual to use Count (Distinct) I'm getting a more accurate number, although it also doesn't seem to take the Team into account.

**To Reproduce**
1. Go to Forecast
2. See the current backlog size in the top right
3. Compare this to the actual backlog in Azure DevOps
4. See that these numbers do not match up

**Expected behavior**
I expect this to match the number of backlog items I actually have on my backlog

**Screenshots**
Backlog in Azure DevOps:

![Screenshot 2021-07-20 at 15 02 28](https://user-images.githubusercontent.com/1225489/126328807-e2243c20-c9a8-44ae-8a55-4a8bb06afdf5.png)

Current Backlog Size in FlowViz:

![Screenshot 2021-07-20 at 15 02 06](https://user-images.githubusercontent.com/1225489/126328734-7185c89b-355c-40bf-a246-3fde37a39809.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] Latest version downloaded from GitHub

**Additional context**
As I mentioned changing the visual to use Count (Distinct) I get a number that matches with Azure DevOps (off by one, but I guess there might be a synchronization delay for Analytics, not sure). It also doesn't take the Team dimension into account, but I'll file a separate issue for that.

**Comment by nbrown02** [comment]
Thanks for reporting this one, a good spot! Fixed in latest version :)

**Comment by jmezach** [comment]
Thanks for the quick action. I've also managed to fix the Team issue by making sure that that filter also influences the current backlog size visual by using Edit Interactions.
