### ISSUE TITLE
Git commits should include some kind of description other than "Add Files Via Upload"

### ISSUE THREAD

**Issue by aayaffe** [nbrown02/FlowViz#37]
For a better understanding of changes done to project files, new features and bug fixes, a proper commit message should be attached to every change made in the repository.
Thank you in advance

**Comment by nbrown02** [comment]
Apologies - I will do it going forward, first person to ever point it out!

**Comment by aayaffe** [comment]
With pleasure.
Thank you for the great work!

**Comment by nbrown02** [comment]
And my latest one followed your advice :)

**Comment by aayaffe** [comment]
Glad to hear it!
