### ISSUE TITLE
400 Bad request- blocked is not available

### ISSUE THREAD

**Issue by iandavies123** [nbrown02/FlowViz#40]
I've downloaded the latest version and when authenticating i am getting the below issue. Is this soemthing youve ever come across before?

Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: 
OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403522: The property 'Blocked' is not available on the specified Project(s). Please remove 'Blocked' from your query and try again..)
OData Version: 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403522: The property 'Blocked' is not available on the specified Project(s). Please remove 'Blocked' from your query and try again..)

**Comment by iandavies123** [comment]
Seems this is down to project (more like process) configuration. We have multiple projects and some work and others dont in relation to this field. The blocked field doesnt seem to exist in some projects. Feel free to close

**Comment by nbrown02** [comment]
Hi there, thanks for raising this.

Could you help me out with what process template you are using and if you're an Azure DevOps/Server/TFS user?

**Comment by iandavies123** [comment]
Its Azure Devops. Our setup is a bit all over the place.

The ones that work use a process inherited from the "Scrum (default)" template. The one that isnt working is inherited from a template called "Agile" which i don't know if this is a custom thing or something out of the box

**Comment by nbrown02** [comment]
Perfect thank you. I will try to replicate and get back to you.

As an interim workaround, you can click transform data and edit the source queries, removing the word "blocked" from the queries of:
- WorkItems Blocked
- WorkItems Daily Blocked Count

However this does require a little savvy-ness of Power BI...

**Comment by iandavies123** [comment]
Thanks @nbrown02 

I was looking at that jjust now. I assume this is going to make the blocked report somewhat redundant? We typically use a tag for blocked as opposed for this field (even in the projects wgere it does exist)

**Comment by nbrown02** [comment]
So if you use the blocked tag it absolutely will still work (I originally built it for teams that blocked work this way) 😀 

I then tried to account for teams who use the blocked field, however it creates challenges like this one 😩

**Comment by iandavies123** [comment]
Ah Ok, i shall give that a try now then, thank you so much for replying so quickly

The reports are great btw. I started to build my own version on our "tech develops" training days and within an hour stumbled across this which made things so much easier :)

**Comment by nbrown02** [comment]
No problem - I'm always keen to use feedback, even if it is when things are broken (sorry again).

Glad you like them, exactly the reason why it's free to all 😃

**Comment by nbrown02** [comment]
@iandavies123 can you try [this version](https://1drv.ms/u/s!AjPC43sChgyKglDn2hA59cpj7teK) - will need you to download

**Comment by iandavies123** [comment]
It doesnt work. I get the following errors

WorkItems Bl0cked
Access to the resource is forbidden.
WorkItems Daily Blocked Count
Access to the resource is forbidden.

**Comment by nbrown02** [comment]
Thanks for checking, that helps. I'll make some tweaks for a new version

**Comment by nbrown02** [comment]
Fixed in the latest version @iandavies123 👍
