### ISSUE TITLE
Data loading fails in Organization template (All projects using Agile process template)

### ISSUE THREAD

**Issue by wertzui** [nbrown02/FlowViz#41]
**Describe the bug**
When trying to load the data in the Organization version, the following error is thrown:
```
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403522: The property 'Blocked' is not available on the specified Project(s). Please remove 'Blocked' from your query and try again..) OData Version: 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403522: The property 'Blocked' is not available on the specified Project(s). Please remove 'Blocked' from your query and try again..)
```
The project version is working without any problems.

**To Reproduce**
1. Use the latest Organization version (I also tested the last 3 versions with the same outcome)
2. Enter `analytics.dev.azure.com` and your organization and click Load.
3. Error is thrown

**Expected behavior**
Data is loaded and no error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - FlowViz version 3e18fcba863591ebeb686d60a16439baa2b91d0f
 - Power BI Desktop Version  2.96.1061.0 64-bit (August 2021)

**Additional context**
FlowViz Organization version from 2020-12-14 is working without errors.

**Comment by nbrown02** [comment]
Thanks @wertzui 

Just to check - the projects within your organisation, are they all using the Agile process template? Thats the only way I can see this bug occurring...

**Comment by wertzui** [comment]
Yes, we are using the Agile process template

**Comment by nbrown02** [comment]
Ok - I've not come across an organisation using Azure DevOps that way before. 

In this instance, I won't be fixing it - the current query provides far better performance than the previous one, so I'd rather stick with it as it caters to nearly every use case. 

If it helps, I've tweaked the latest version so it works for you, which is available [here](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Organization%20-%20Agile%20Process%20Only).pbit). For future versions I won't be doing the same, however all you need to do is remove 'Blocked' from the queries :)

**Comment by nbrown02** [comment]
Won't fix but provided a workaround :)
