### ISSUE TITLE
Projects Missing From WorkItems WIP Age

### ISSUE THREAD

**Issue by jcaravella** [nbrown02/FlowViz#47]
Data for only 6 of or 33 projects is appearing in **WorkItems WIP Age** so nothing appears on the Daily WIP panels.  All 33 projects appear in **WorkItems In Progress** and **WorkItems In Progress2**.  All 33 projects are using the same AzDO Process and the **In Progress** states are **Active** and **Resolved**.

Please let me know how to troubleshoot how data gets into **WorkItems WIP Age**.

**Comment by jcaravella** [comment]
Yes, I used the Org template and yes all teams are following scrum and assigning user stories to iteration paths.

**Comment by jcaravella** [comment]
Here are the WITs we use:
![WI Types](https://user-images.githubusercontent.com/7049015/153497946-a3794f96-91a4-4a3e-a9c2-01749c2d96a4.png)

**Comment by jcaravella** [comment]
The hierarchy we follow is:
>Theme
-->Epic
--->Feature
---->Story

**Comment by nbrown02** [comment]
Hmm - are the states mapped correctly to the right state category? So long as they are mapped to the InProgress state category they will appear...

<img width="422" alt="Screenshot 2022-02-10 at 21 33 00" src="https://user-images.githubusercontent.com/29369962/153500209-64672066-f0b3-4617-83d3-abe333996b80.png">

**Comment by jcaravella** [comment]
![image](https://user-images.githubusercontent.com/7049015/153502298-2ac04e59-570d-46d1-a11f-f537662d8a66.png)
And here are the Stories in Current Sprint that are not showing up:
![image](https://user-images.githubusercontent.com/7049015/153502447-f93c1e38-99ea-4c1a-ae0d-def2279dbbb2.png)

**Comment by jcaravella** [comment]
I just refreshed and selected that Project and get 
![image](https://user-images.githubusercontent.com/7049015/153503641-2053f9fc-ff5f-429c-ad79-25a36d200ffb.png)

**Comment by nbrown02** [comment]
Ahhhh ok - hmm that's definitely not correct. Just out of interest, when you look at that project using the project template, how does it look?

**Comment by jcaravella** [comment]
I haven't tried that. Let me download that template and try.

**Comment by jcaravella** [comment]
Using the Project Template Workitesm WIP Age has 9,668 rows and looks like this: 
![image](https://user-images.githubusercontent.com/7049015/153505246-2d67ee0f-b4cd-4823-8690-3e5de6b5e846.png)

**Comment by nbrown02** [comment]
So it looks to be working for Project and not for Organization? This is the same result I see but still not sure why!

Let me continue to investigate...

**Comment by jcaravella** [comment]
Ok. I compared to two queries and the only difference I see is & Project &

One observation is my org template Workitems WIP Age table has exactly 10K rows. Is there something that's limiting the rows returned in the org template?

**Comment by nbrown02** [comment]
I'm glad your analysis was the same as mine! :D 

So one of the things I did was change the DateValue in the query so it was a shorter date range:

<img width="1000" alt="Screenshot 2022-02-11 at 07 36 01" src="https://user-images.githubusercontent.com/29369962/153553240-f4f337fe-c8a3-4842-9316-8c226e486d6d.png">

It then worked for me, but obviously how many projects people have in a collection varies! 

My suspicion is Microsoft limit it to 10,000 rows...

**Comment by jcaravella** [comment]
The problem appears to be because you are using WorkItemSnapshot instead of WorkItemRevisions:

VS403510: The Snapshot tables in Analytics are intended to be used only in an aggregation.  The result for this query has been reduced to preview of a single result page. Details on recommended query patterns are available here: https://go.microsoft.com/fwlink/?linkid=861060

Moving the date won't help me. Unfortunately, I won't be able to use this incredible report for my org : (

**Comment by nbrown02** [comment]
Ah yes good spot - I'll continue to investigate to see if there are other ways it can be solved :)

**Comment by jcaravella** [comment]
Another observation after you publish.  Even if I make the date Jan 1st, scheduled refreshes fail every time.

Failure details: OData: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

**Comment by nbrown02** [comment]
Yes I think I'm limited somewhat by a small dataset in my test collection :D 

I've asked Microsoft if there is an alternative query I could use...

**Comment by jcaravella** [comment]
Brilliant!  You did fix it. I'm getting ~650K rows in  Workitems WIP Age now.  I also published and tested a scheduled refresh and it works as well (although there is something wonky with Last Refresh date/time when you do a scheduled refresh that I'll try to figure out).

I'm going to start rolling this out to my org next week (however, I would like to figure out how to sync the slicers for a better user experience).

Great work. Cheers, mate!

**Comment by nbrown02** [comment]
Awesome! Thank you for responding so quickly with what you were seeing at your end too, this was definitely a much bigger dataset than I have (17,000 rows) so good to validate. Going to take a look at slicer syncing in the coming days too :)
