### ISSUE TITLE
WorkItems Daily Blocked Count missing data

### ISSUE THREAD

**Issue by jcaravella** [nbrown02/FlowViz#48]
WorkItems Daily Blocked Count is being restricted to 10K rows in the Org Template version.  I fixed it using the following query:

let
    Source = OData.Feed(#"Http/Https" & "://" & #"Analytics URL/Azure DevOps Server" & "/" & Organization & "/_odata/v3.0-preview/WorkItemSnapshot?%20$apply=filter(%20StateCategory%20eq%20%27InProgress%27%20and%20WorkItemType%20ne%20%27Issue%27%20and%20WorkItemType%20ne%20%27Task%27%20and%20WorkItemType%20ne%20%27Test%20Case%27%20and%20WorkItemType%20ne%20%27Test%20Plan%27%20and%20WorkItemType%20ne%20%27Shared%20Parameter%27%20and%20WorkItemType%20ne%20%27Shared%20Steps%27%20and%20WorkItemType%20ne%20%27Test%20Suite%27%20and%20WorkItemType%20ne%20%27Impediment%27%20and%20WorkItemType%20ne%20%27Epic%27%20and%20WorkItemType%20ne%20%27Feature%27%20and%20DateValue%20ge%202021-08-01Z%20)
    /groupby(%20(Blocked,DateValue,DateSK,AreaSK,IterationSK,TagNames),%20aggregate($count%20as%20Count)%20)", null, [Implementation="2.0"]),
    #"Filtered Rows" = Table.SelectRows(Source, each true),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"DateValue", type date}})
in
    #"Changed Type"

Please let me know if you see any issues with this query change.

**Comment by nbrown02** [comment]
Awesome thanks Joe - will make this change tomorrow and republish 🤩

**Comment by nbrown02** [comment]
Now fixed :)
