### ISSUE TITLE
Pipeline Analytics support

### ISSUE THREAD

**Issue by awentzel** [nbrown02/FlowViz#7]
Is there an intention for this project to continue? There hasn't been recent activity. 

There are a lot of great analytics being added for pipelines now as well.  Any plans to tackle this support with an example?

I'm really glad I found this template, it's made it so much easier than manually creating myself. 

Thanks,

**Comment by nbrown02** [comment]
@awentzel thanks for reaching out. I am working on a revised template which will make navigation easier (using buttons in Power BI). I was hoping the DORA metrics would be possible using the Pipelines Analytics but doesn't look like that data is there (yet). What metrics would you like to see?

**Comment by nbrown02** [comment]
Closing this as no further feedback received, long term I will aim to introduce DORA metrics once available via the API

**Comment by nbrown02** [comment]
@awentzel I've started another repo with some sample OData reports for Pipelines - [feel free to check it out 👍 ](https://github.com/nbrown02/AzureDevOps-OData-SampleReports)
