### ISSUE TITLE
Forecast tab crash when you try to turn of focus mode.

### ISSUE THREAD

**Issue by ramsaytom** [nbrown02/FlowViz#71]
**Describe the bug**
Forecast tab crash when you try to turn of focus mode.

**To Reproduce**
1. Go to forecast tab on the Flowviz 'project'
2. Click on on Forecast tab
3. click on focus 
4. causes powerbi to crash. I have also tried duplicate the tab to look at predicting effort points however when I tried to delete a field it causes powerbi to crash as well.

**Expected behavior**
Should open in focus mode 

**Desktop (please complete the following information):**
desktop version. this chart also doesnt work in the web view either. all other charts work

Any help you could give on this would be greatly appreciated. over all thou great template thank you.

**Comment by nbrown02** [comment]
Thanks for sharing this @ramsaytom - the only change I can make to prevent this would be to turn off focus mode. Would that be an issue?

**Comment by nbrown02** [comment]
Disabled focus mode to prevent this happening

**Comment by ramsaytom** [comment]
Thanks for this @nbrown02, i am currently using the Project level report  and have downloaded your new version. However the focus mode still appears to be on the forecast chart?
![Forecast Focus mode still showing](https://user-images.githubusercontent.com/101855332/159632486-5d7f2856-5373-42ee-9ec4-e03f6c4df64e.jpg)

**Comment by nbrown02** [comment]
Hmm - it's definitely disabled. I noticed this:
<img width="311" alt="Screenshot 2022-03-23 at 07 46 02" src="https://user-images.githubusercontent.com/29369962/159649096-2092c60c-b791-4a16-98bf-68a6d0b28466.png">

So likely means in desktop view you'll still see it?
