### ISSUE TITLE
OData Request Failed 

### ISSUE THREAD

**Issue by marissatw** [nbrown02/FlowViz#80]
I am getting this error when trying to load the data.

![image](https://user-images.githubusercontent.com/112510390/187513654-6a9890f7-a0d1-4ad3-a2ad-24ecc4aeef16.png)

I have tried going through the closed issues to see if there were any solutions already presented, but I have yet to see anything related to my issue. I think it may have to do with the way I logged in but I'm not sure how to re-do that process. I tried to re-download and start the process over, but that did not help. If you could provide some assistance, that would be much appreciated! Thank you!

**Comment by nbrown02** [comment]
Hi there,

Thanks for reaching out :)

If you go to Transform Data > Edit parameters it will show you what you've entered:
![image](https://user-images.githubusercontent.com/29369962/187520644-722b343b-330c-4f62-9670-ae360a19189d.png)


When correct, it should look something like this:
![image](https://user-images.githubusercontent.com/29369962/187520690-1a3b7a72-abbf-43d0-a139-ce97715e839e.png)

**Comment by marissatw** [comment]
Those parameters I believe are correct, but I’m still getting the same error unfortunately :/

**Comment by nbrown02** [comment]
Can you email me (nicolas.brown@outlook.com) the parameters (I imagine they are sensitive that's all!) as well as the full error message?
Thanks

**Comment by nbrown02** [comment]
Closing this as not heard a response
