### ISSUE TITLE
Work item types to include Tasks

### ISSUE THREAD

**Issue by cmohams9** [nbrown02/FlowViz#82]
**Is your feature request related to a problem? Please describe.**
For our SCRUM project, we would like to track the work items to the level of tasks. Currently, we are unable to see 'tasks' under work item types.

**Describe the solution you'd like**
Include 'Tasks' work item type to all the queries.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/92427489/191062566-d910b1a2-c547-4dcf-8591-247efe16ab1a.png)

**Comment by nbrown02** [comment]
This won't be something I will be building I'm afraid. For more on why [please see my answer as to why in the FAQs.](https://github.com/nbrown02/FlowViz/wiki/7.-FAQs#how-come-tasks-work-item-type-are-not-included)

If you want to include Tasks, you need to remove the section of the query that excludes Task work item types and to do this for every table that includes 'WorkItems':

![image](https://user-images.githubusercontent.com/29369962/191064172-cb1d0b1d-1d15-4e5a-a83f-00cc178b3ac2.png)

**Comment by cmohams9** [comment]
Thank you and appreciate the quick response!


From: Nick Brown ***@***.***>
Date: Monday, 19 September 2022 at 8:15 PM
To: nbrown02/FlowViz ***@***.***>
Cc: Sujith Mohammed ***@***.***>, Author ***@***.***>
Subject: Re: [nbrown02/FlowViz] Work item types to include Tasks (Issue #82)

This won't be something I will be building I'm afraid. For more on why please see my answer as to why in the FAQs.<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnbrown02%2FFlowViz%2Fwiki%2F7.-FAQs%23how-come-tasks-work-item-type-are-not-included&data=05%7C01%7CSujith.Mohammed%40jci.com%7C7d12dbdfe3054681b98b08da9a5a1fe2%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637992009114853454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vOLioTiNYxBX4OPyj2fuE1ZTBGYL7HDJOI1MU54%2BK4M%3D&reserved=0>

If you want to include Tasks, you need to remove the section of the query that excludes Task work item types and to do this for every table that includes 'WorkItems':

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29369962%2F191064172-cb1d0b1d-1d15-4e5a-a83f-00cc178b3ac2.png&data=05%7C01%7CSujith.Mohammed%40jci.com%7C7d12dbdfe3054681b98b08da9a5a1fe2%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637992009114853454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2lL6K72skXTxXhdCR7wXcL92ohL%2FviqUlZB0DYwQ%2BVI%3D&reserved=0>
