### ISSUE TITLE
Forecast Issue

### ISSUE THREAD

**Issue by sarawomski** [nbrown02/FlowViz#86]
**Describe the bug**
I'm trying to update the Forecast data to use a custom Completed date. However, when adding the custom Completed date the visual will go blank. I then try to Edit the visual and I get an error message.

**To Reproduce**
1. Go to the Forecast tab
2. Click on first visual (D3JSVisual)
3. Change the count of Completed Date to count of another date
4. Visual blanks out
5. Click the ellipses
6. Click Edit
7. See error in screenshot and log details under Additional Context

**Expected behavior**
I should be able to change the Date for the visual and be able to Edit the visual.

**Screenshots**
When trying to edit the first D3JSVisual: 
![image](https://user-images.githubusercontent.com/88736640/201178726-d7d5e383-9535-4a19-97e2-95d99734e3cc.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 2.110.1161.0 64-bit (October 2022)

**Additional context**
Log information: [FrownSnapShot210252b4-c068-42b1-8d4e-1b6f59052139.zip](https://github.com/nbrown02/FlowViz/files/9983742/FrownSnapShot210252b4-c068-42b1-8d4e-1b6f59052139.zip)

**Comment by sarawomski** [comment]
Would you be able to share the code used in both of the D3JSVisuals?

**Comment by nbrown02** [comment]
Hi there,

Thanks for this. Unfortunately this isn't anything within my control as it's down to a bug with the D3 visual.

That being said, there is a workaround I have found to get this working for me, here are the steps, using the ResolvedDate field as an example.

1. Change WorkItemsCompleted table to load ResolvedDate and ResolvedDateSK (in addition to other columns)
2. Once data has loaded, remove all D3 visuals on the forecast page
3. Remove CompletedDate and CompletedDateSK columns
4. Rename ResolvedDate to CompletedDate and ResolvedDateSK to CompletedDateSK
5. Create a relationship between Dates [DateSK] and WorkItems Completed [CompletedDateSK]
6. Load a new FlowViz template
7. On the new template, select the D3 visuals from the forecast page and hit 'copy'
8. In the original report (using ResolvedDate), paste into the Forecast page

Hope that helps - a bit long winded but the best I can do :)

**Comment by nbrown02** [comment]
Code for When Will It Be Done:
Javascript:
`function replaceNulls(data) {
	for (var i=0; i<data.length; i++) {
		if (data[i].countofcompleteddate === 'null') {
			data[i].countofcompleteddate = '0';
		}

		if (data[i].numberofremainingitems === 'null') {
			data[i].numberofremainingitems = '0';
		}

		// convert to int
		data[i].countofcompleteddate = parseInt(data[i].countofcompleteddate);
		data[i].numberofremainingitems = parseInt(data[i].numberofremainingitems);
	}
}

function getThroughput(data) {
	var throughput = [];

	for (var i = 0; i < data.length; ++i) {
		throughput.push(data[i].countofcompleteddate);
	}
	return throughput;
}

function time_for_jobs(items, throughput) {
    // Randomly selects a number of jobs
    var count = 0;
    var loop = true;
    while (loop){
        items -= throughput[Math.floor(Math.random()*throughput.length)]
        count += 1;
        if (items <= 0){
            loop = false;
        }
    }
    return count;
}

function monte_carlo(iterations, items, throughput){
    // Performs a Monte Carlo simulation
    var output = [];
    for (var i=0; i<iterations; i++) {
        output.push(time_for_jobs(items, throughput));
    }
    return output;
        
}

function freq_table(output){
    // Creates a frequency table from MC output
    var result = {};
    for (var i=0; i<d3.max(output); i++){
         result[i] = 0; // Initialise to zeros
    }
    for(var i = 0; i < output.length; ++i) {
        if (!result[output[i]]) {
            result[output[i]] = 0;
        }
        ++result[output[i]]; // Increment
    }
    return result;
}

function format(data){
    // Gets monte carlo frequency table in correct plotting format
    var final = [];
    Object.entries(data).forEach(function(key, val) {
        final.push({
            "num" : key[0],
            "freq" : key[1]
        });
    });
    return final;
}

function sortNumber(a, b) {
  return a - b;
}

function validation(samples){
    samples.sort(sortNumber);
    var group1Sum = 0;
    var group1Count = 0;
    var group2Sum = 0;
    var group2Count = 0;
    var range = Math.max.apply(null, samples) - Math.min.apply(null, samples);
    
    for(var i = 0; i < samples.length; ++i){
        if (i % 2 == 0) {
            group1Sum += samples[i];
            group1Count ++;
        } else {
            group2Sum += samples[i];
            group2Count ++;
        }
    }

    var group1avg = group1Sum / group1Count;
    var group2avg = group2Sum / group2Count;
    var avgError = Math.abs(group1avg - group2avg);
    var stability = (avgError / range) * 100;
    return stability.toFixed(1);
}

function calc_median(numbers) {
    // median of [3, 5, 4, 4, 1, 1, 2, 3] = 3
    var median = 0, numsLen = numbers.length;
    numbers.sort(sortNumber);
 
    if (
        numsLen % 2 === 0 // is even
    ) {
        // average of two middle numbers
        median = (numbers[numsLen / 2 - 1] + numbers[numsLen / 2]) / 2;
    } else { // is odd
        // middle number only
        median = numbers[(numsLen - 1) / 2];
    }
 
    return median;
}

function calc_percentile(numbers, perc) {
    var numsLen = numbers.length;
    var percentile_index = (perc * numsLen)-1;
    numbers.sort(sortNumber);

    //percentile = Math.ceil((numbers[Math.floor(percentile_index)] + numbers[Math.ceil(percentile_index)]) / 2);
    var percentile = Math.ceil(numbers[Math.floor(percentile_index)] + (numbers[Math.ceil(percentile_index)] - numbers[Math.floor(percentile_index)]) * percentile_index % 1);
    return percentile;
}

function x_ticks(x_vals, delta){
    // removes every delta'th element for x axis
    var domain = [];
    for (var i=0; i<x_vals.length; i=i+delta){
        domain.push(x_vals[i]);
    }
    return domain;
}

// Define margin, width and height of box
var margin = {top: 20, right: 75, bottom: 50, left: 80},
    width = pbi.width - margin.left - margin.right,
    height = pbi.height - margin.top - margin.bottom;

var bar_gap = 0.1;
// Define scales
var x = d3.scale.ordinal()
            .domain([0,width])
            .rangeRoundBands([0, width], bar_gap, 0);
var y = d3.scale.linear()
            .range([height, 0]);

// Create chart based on margin, width, height
var svg = d3.select("#chart")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");


// Read in data
pbi.dsv(function(data) {
  
    // Initialize parameters
	replaceNulls(data);
	var throughput = getThroughput(data);
    var projection_items = Math.max.apply(Math, data.map(function(o) { return o.numberofremainingitems;})); // select max as nulls are replaced with 0s.
    var iterations = 10000;

    // Run the simulation
    var stability = validation(throughput);
    var mc = monte_carlo(iterations, projection_items, throughput);
    var ft = freq_table(mc);
    var histogram = format(ft);

    // Determine percentiles
    var median = calc_median(mc);
  	var seventy_percent = calc_percentile(mc, 0.7);
  	var seventy_five_percent = calc_percentile(mc, 0.75);
    var eighty_five_percent = calc_percentile(mc, 0.85);
    var ninety_five_percent = calc_percentile(mc, 0.95);

    // Domains of each axis
    x.domain(Object.keys(ft));
    y.domain([0, d3.max(Object.values(ft))]);
  
  	var _interval = Math.round(Object.keys(ft).length / 7);
    
    // Add axes to graph
    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.svg.axis()
              .tickValues(x_ticks(Object.keys(ft), _interval)) // Determines x-axis skips (arg 2)
              .scale(x)
              .orient("bottom"));
    // text label for the x axis
    svg.append("text")             
        .attr("transform",
              "translate(" + (width/2) + " ," + 
                             (height + margin.top + 20) + ")")
        .style("text-anchor", "middle")
        .text("Weeks to complete "+projection_items.toString()+" work items | Stability = " + stability.toString() + "% (keep below 25%)")
    .style("font-size", "12px")
  	.attr("class", "label xAxisLabel");

    svg.append("g")
        .attr("class", "y axis")
        .call(d3.svg.axis()
              .scale(y)
              .orient("left"));
    // text label for the y axis
    svg.append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 0 - margin.left)
        .attr("x",0 - (height / 2))
        .attr("dy", "1em")
        .style("text-anchor", "middle")
        .text("Frequency")
    .style("font-size", "12px")
  	.attr("class", "label yAxisLabel");
    
    // Add data to the graph from Monte Carlo histogram
    svg.selectAll(".bar")
        .data(histogram)
            .enter()
        .append("rect")
            //.attr("class", "bar")
            .attr("x", function(d) { return x(d.num)})
            .attr("width", x.rangeBand())
            .attr("y", function(d) { return y(d.freq)})
            .attr("height", function(d) { return height - y(d.freq); })
			.attr("class", function(d) {
    			if (d.num <= median) {
                	return "bar barRed";
                } else if (d.num > median & d.num <= seventy_percent) {
                    return "bar barOrange";
                } else if (d.num > seventy_percent & d.num < eighty_five_percent) {
                	return "bar barYellow";
                } else {
                  	return "bar barGreen";
                }
    		});
    
    // Add the percentile lines on the graph
//    var group = svg.append("g");
//    var line = d3.svg.line()
//        .x(function(d){ return d.x})
//        .y(function(d){ return d.y})
    
//    var zeroth_pxl =  x(histogram[0].num); // Pixel position of first bar
//    var pxl_diff = x(histogram[1].num) - zeroth_pxl; // Rate of pixel increase per bar
//    var bar_centre = pxl_diff/2;
    
// Percentile data    
//    var data_50 = [ // 0.5 added to px_diff for the mean
//        {x: zeroth_pxl+bar_centre+(pxl_diff*median), y:10},
//        {x: zeroth_pxl+bar_centre+(pxl_diff*median), y:height}
//    ]
//    var data_85 = [ // 0.85 added to px_diff for the 85th %ile
//        {x: zeroth_pxl+bar_centre+(pxl_diff*eighty_five_percent), y:10},
//        {x: zeroth_pxl+bar_centre+(pxl_diff*eighty_five_percent), y:height}
//    ]
//    var data_95 = [ // 0.95 added to px_diff for the 95th %ile
//        {x: zeroth_pxl+bar_centre+(pxl_diff*ninety_five_percent), y:10},
//        {x: zeroth_pxl+bar_centre+(pxl_diff*ninety_five_percent), y:height}
//    ]

    // Percentile lines
 //   group.selectAll("path")
 //       .data([data_50, data_95, data_85])
 //           .enter()
 //       .append("path")
 //         .attr("d", line)
 //         .attr("stroke", "black")
 //         .attr("fill", "none")
 //         .attr("stroke-width", 1)
 //         .attr("stroke-dasharray", "5,5")
 
 // Labels for 50th percentile
 //   group.append("text")
 //     .attr("dx", zeroth_pxl+bar_centre+(pxl_diff*median)-10) // Minus 10 for centering
 //     .attr("dy", 0)
 //     .text("50%")
 //     .style("font-size", "10px")
 // 	  .attr("class", "label fiftyPerc");
  
 // Labels for 85th percentile   
 //   group.append("text")
 //     .attr("dx", zeroth_pxl+bar_centre+(pxl_diff*eighty_five_percent)-10) // Minus 10 for centering
 //     .attr("dy", 0)
 //     .text("85%")
 //     .style("font-size", "10px")
 // 	  .attr("class", "label eightyFivePerc");
 
 // Labels for 95th percentile
 //   group.append("text")
 //     .attr("dx", zeroth_pxl+bar_centre+(pxl_diff*ninety_five_percent)-10) // Minus 10 for centering
 //     .attr("dy", 0)
 //     .text("95%")
 //     .style("font-size", "10px")
 // 	  .attr("class", "label ninetyFivePerc");
            
});`

Style:
`body {
  font-family: "Segoe UI";
  font-size: 10px;
}

.axis path,
.axis line {
  fill: none;
  stroke: black;
  shape-rendering: crispEdges;
}

.axis text {
  font-family: "Segoe UI";
  fill: black
}

.axis {
  font-size: 10px;
}

.barRed {
  fill: #e15759
}

.barOrange {
  fill: #f28e2b
}

.barYellow {
  fill: #edc948
}

.barGreen {
  fill: #59a14f
}

.label {
  font-family: "Segoe UI";
  fill: black
}`

Code for What Will We Get:
Javascript:
`function replaceNulls(data) {
	for (var i=0; i<data.length; i++) {
		if (data[i].countofcompleteddate === 'null') {
			data[i].countofcompleteddate = '0';
		}

		if (data[i].numberofweeks === 'null') {
			data[i].numberofweeks = '0';
		}

		// convert to int
		data[i].countofcompleteddate = parseInt(data[i].countofcompleteddate);
		data[i].numberofweeks = parseInt(data[i].numberofweeks);
	}
}

function getThroughput(data) {
	var throughput = [];

	for (var i = 0; i < data.length; ++i) {
		throughput.push(data[i].countofcompleteddate);
	}
	return throughput;
}

function jobs_in_weeks(weeks, throughput) {
    // Randomly selects a number of jobs
    var count = 0;
    for (var i=0; i<weeks; i++){
        count += throughput[Math.floor(Math.random()*throughput.length)];
    }
    return count
}

function monte_carlo(iterations, weeks, throughput){
    // Performs a Monte Carlo simulation
    var output = [];
    for (var i=0; i<iterations; i++) {
        output.push(jobs_in_weeks(weeks, throughput));
    }
    return output;
        
}

function freq_table(output){
    // Creates a frequency table from MC output
    var result = {};
    for (var i=0; i<d3.max(output); i++){
         result[i] = 0; // Initialise to zeros
    }
    for(var i = 0; i < output.length; ++i) {
        if (!result[output[i]]) {
            result[output[i]] = 0;
        }
        ++result[output[i]]; // Increment
    }
    return result;
}

function format(data){
    // Gets monte carlo frequency table in correct plotting format
    var final = [];
    Object.entries(data).forEach(function(key, val) {
        final.push({
            "num" : key[0],
            "freq" : key[1]
        });
    });
    return final;
}

function sortNumber(a, b) {
  return a - b;
}

function validation(samples){
    samples.sort(sortNumber);
    var group1Sum = 0;
    var group1Count = 0;
    var group2Sum = 0;
    var group2Count = 0;
    var range = Math.max.apply(null, samples) - Math.min.apply(null, samples);
    
    for(var i = 0; i < samples.length; ++i){
        if (i % 2 == 0) {
            group1Sum += samples[i];
            group1Count ++;
        } else {
            group2Sum += samples[i];
            group2Count ++;
        }
    }

    var group1avg = group1Sum / group1Count;
    var group2avg = group2Sum / group2Count;
    var avgError = Math.abs(group1avg - group2avg);
    var stability = (avgError / range) * 100;
    return stability.toFixed(1);
}

function calc_median(numbers) {
    // median of [3, 5, 4, 4, 1, 1, 2, 3] = 3
    var median = 0, numsLen = numbers.length;
    numbers.sort(sortNumber);
 
    if (
        numsLen % 2 === 0 // is even
    ) {
        // average of two middle numbers
        median = (numbers[numsLen / 2 - 1] + numbers[numsLen / 2]) / 2;
    } else { // is odd
        // middle number only
        median = numbers[(numsLen - 1) / 2];
    }
 
    return median;
}

function calc_percentile(numbers, perc) {
    var numsLen = numbers.length;
    var percentile_index = (perc * numsLen)-1;
    numbers.sort(sortNumber);

    //percentile = Math.ceil((numbers[Math.floor(percentile_index)] + numbers[Math.ceil(percentile_index)]) / 2);
    var percentile = Math.ceil(numbers[Math.floor(percentile_index)] + (numbers[Math.ceil(percentile_index)] - numbers[Math.floor(percentile_index)]) * percentile_index % 1);
    return percentile;
}

function x_ticks(x_vals, delta){
    // removes every delta'th element for x axis
    var domain = [];
    for (var i=0; i<x_vals.length; i=i+delta){
        domain.push(x_vals[i]);
    }
    return domain;
}

// Define margin, width and height of box
var margin = {top: 20, right: 75, bottom: 50, left: 80},
    width = pbi.width - margin.left - margin.right,
    height = pbi.height - margin.top - margin.bottom;

var bar_gap = 0.1;
// Define scales
var x = d3.scale.ordinal()
            .domain([0,width])
            .rangeRoundBands([0, width], bar_gap, 0);
var y = d3.scale.linear()
            .range([height, 0]);

// Create chart based on margin, width, height
var svg = d3.select("#chart")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");


// Read in data
pbi.dsv(function(data) {
  
    // Initialize parameters
	replaceNulls(data);
	var throughput = getThroughput(data);
    var projection_weeks = Math.max.apply(Math, data.map(function(o) { return o.numberofweeks;}));
    var iterations = 10000;

    // Run the simulation
    var stability = validation(throughput);
    var mc = monte_carlo(iterations, projection_weeks, throughput);
    var ft = freq_table(mc);
    var histogram = format(ft);

    // Determine percentiles
    var median = calc_median(mc);
  	var seventy_percent = calc_percentile(mc, 1-0.7);
  	var seventy_five_percent = calc_percentile(mc, 1-0.75);
    var eighty_five_percent = calc_percentile(mc, 1-0.85);
    var ninety_five_percent = calc_percentile(mc, 1-0.95);

    // Domains of each axis
    x.domain(Object.keys(ft));
    y.domain([0, d3.max(Object.values(ft))]);
  
   	var _interval = Math.round(Object.keys(ft).length / 7);
    
    // Add axes to graph
    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.svg.axis()
              .tickValues(x_ticks(Object.keys(ft), _interval)) // Determines x-axis skips (arg 2)
              .scale(x)
              .orient("bottom"));
    // text label for the x axis
    svg.append("text")             
        .attr("transform",
              "translate(" + (width/2) + " ," + 
                             (height + margin.top + 20) + ")")
        .style("text-anchor", "middle")
        .text("Work items completed in " + projection_weeks.toString() + " weeks | Stability = " + stability.toString() + "% (keep below 25%)")
    .style("font-size", "12px")
  	.attr("class", "label yAxisLabel");

    svg.append("g")
        .attr("class", "y axis")
        .call(d3.svg.axis()
              .scale(y)
              .orient("left"));
    // text label for the y axis
    svg.append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 0 - margin.left)
        .attr("x",0 - (height / 2))
        .attr("dy", "1em")
        .style("text-anchor", "middle")
        .text("Frequency")
    .style("font-size", "12px")
  	.attr("class", "label yAxisLabel");
    
    // Add data to the graph from Monte Carlo histogram
    svg.selectAll(".bar")
        .data(histogram)
            .enter()
        .append("rect")
            //.attr("class", "bar")
            .attr("x", function(d) { return x(d.num)})
            .attr("width", x.rangeBand())
            .attr("y", function(d) { return y(d.freq)})
            .attr("height", function(d) { return height - y(d.freq); })
  			.attr("class", function(d) {
    			if (d.num >= median) {
                	return "bar barRed";
                } else if (d.num < median & d.num >= seventy_percent) {
                    return "bar barOrange";
                } else if (d.num < seventy_percent & d.num > eighty_five_percent) {
                	return "bar barYellow";
                } else {
                  	return "bar barGreen";
                }
    		});
    
    // Add the percentile lines on the graph
    var group = svg.append("g");
    var line = d3.svg.line()
        .x(function(d){ return d.x})
        .y(function(d){ return d.y})
    
    var zeroth_pxl =  x(histogram[0].num); // Pixel position of first bar
    var pxl_diff = x(histogram[1].num) - zeroth_pxl; // Rate of pixel increase per bar
    var bar_centre = pxl_diff/2;
    
    
//    var data_50 = [ // 0.5 added to px_diff for the mean
//        {x: zeroth_pxl+bar_centre+(pxl_diff*median), y:10},
//        {x: zeroth_pxl+bar_centre+(pxl_diff*median), y:height}
//    ]
//    var data_85 = [ // 0.85 added to px_diff for the 85th %ile
//        {x: zeroth_pxl+bar_centre+(pxl_diff*eighty_five_percent), y:10},
//        {x: zeroth_pxl+bar_centre+(pxl_diff*eighty_five_percent), y:height}
//    ]
//    var data_95 = [ // 0.95 added to px_diff for the 95th %ile
//        {x: zeroth_pxl+bar_centre+(pxl_diff*ninety_five_percent), y:10},
//        {x: zeroth_pxl+bar_centre+(pxl_diff*ninety_five_percent), y:height}
//    ]

//    group.selectAll("path")
//        .data([data_50, data_95, data_85])
//            .enter()
//        .append("path")
//          .attr("d", line)
//          .attr("stroke", "black")
//          .attr("fill", "none")
//          .attr("stroke-width", 1)
//          .attr("stroke-dasharray", "5,5")
    
//    group.append("text")
//      .attr("dx", zeroth_pxl+bar_centre+(pxl_diff*median)-10) // Minus 10 for centering
//      .attr("dy", 0)
//      .text("50%")
//      .style("font-size", "10px");
    
//    group.append("text")
//      .attr("dx", zeroth_pxl+bar_centre+(pxl_diff*eighty_five_percent)-10) // Minus 10 for centering
//      .attr("dy", 0)
//      .text("85%")
//      .style("font-size", "10px");
    
//    group.append("text")
//      .attr("dx", zeroth_pxl+bar_centre+(pxl_diff*ninety_five_percent)-10) // Minus 10 for centering
//      .attr("dy", 0)
//      .text("95%")
//      .style("font-size", "10px");
            
});`

Style:
`body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: black;
  shape-rendering: crispEdges;
}

.axis text {
  fill: black
}

.axis {
  font: 10px sans-serif;
}

.barRed {
  fill: #e15759
}

.barOrange {
  fill: #f28e2b
}

.barYellow {
  fill: #edc948
}

.barGreen {
  fill: #59a14f
}

.label {
  fill: black
}`

**Comment by sarawomski** [comment]
You are so awesome! Thank you for everything!!

**Comment by nbrown02** [comment]
I realise that is not particularly helpful formatting wise :D 

I put it all into a text file [here](https://drive.google.com/file/d/17XpvHTrZghsyQewiOIDAJrl0dZwotvWh/view?usp=share_link)

**Comment by nbrown02** [comment]
And if you have the time - please feel free to leave a review in the ADO Marketplace or [checkout the online course ](https://flowviz.thinkific.com/courses/fundamentals):)
