### ISSUE TITLE
Error- Data not loading into PowerBI

### ISSUE THREAD

**Issue by priyankshah1410** [nbrown02/FlowViz#87]
Hello,

I am trying to connect FlowViz PowerBI (Project) report, I am able to successfully make the connection.

On the other hand, while the data is loading it gives an error with the details mentioned in the images below:

I have cleared all caches to avail the memory space in powerbi.

Can you please let us know what the possible solution to the given problem might be.

Appreciate your help and response.

Thank you

![image](https://user-images.githubusercontent.com/10057212/204365535-e948ef58-954f-4d95-9a3f-a9b29585b4f5.png)

![image](https://user-images.githubusercontent.com/10057212/204365596-f3d5e9c6-ee36-4446-8204-20f6c106efc1.png)

![image](https://user-images.githubusercontent.com/10057212/204365643-d2bdab32-42f6-4828-8f0f-9c880b905eef.png)

**Comment by nbrown02** [comment]
Hi there,Thanks for sharing. A few questions:- Are you on the latest version of Power BI desktop- The error message mentions modifications to the server - has the report been changed at all?Thanks,NickSent from my iPhoneOn 28 Nov 2022, at 19:39, priyankshah1410 ***@***.***> wrote:﻿
Hello,
I am trying to connect FlowViz PowerBI (Project) report, I am able to successfully make the connection.
On the other hand, while the data is loading it gives an error with the details mentioned in the images below:
I have cleared all caches to avail the memory space in powerbi.
Can you please let us know what the possible solution to the given problem might be.
Appreciate your help and response.
Thank you

**Comment by priyankshah1410** [comment]
Hello Nick,

Thank you for your quick response,

We are using October 2022 version of Power BI, hopefully that's the latest version.
![image](https://user-images.githubusercontent.com/10057212/204369145-a5a4d14f-e6f5-4c1d-a9d7-d291650ed990.png)

I have not made any modification to the report,
Steps performed:
1- Downloaded the PowerBI file
2- fill in the connection details for org and project
3- connection was successful and started loading the data
4- Showed error after loading the data for sometime

**Comment by nbrown02** [comment]
Thank you - ok so let me try to replicate your setup. Can you email me (
***@***.***) screenshots of all the different boards in the
project and associated area paths? Please mask anything sensitive :)

Thanks,

Nick

**Comment by priyankshah1410** [comment]
Step 1: 
Downloaded below file
![image](https://user-images.githubusercontent.com/10057212/204389531-d231eecd-6d06-4d1c-8e27-f631f72b393a.png)

Step 2: 
Opened the file

Step 3: 
Fill in the information below
![image](https://user-images.githubusercontent.com/10057212/204390160-6cffbe8d-6e56-442b-9b94-b6e1c6c6ad2e.png)

Step 4:
Click on Load

Step 5: Data starts loading
![image](https://user-images.githubusercontent.com/10057212/204390797-0754f8bc-1be2-4026-88d3-54df64cdf75b.png)

Step 6: Gives the error after sometime of loading as shown in the previous screenshot of errors.

Let me know if this helps or if you need anything else from my end

PS: I have all required access in AzureDevops to connect to it.

Thank you and appreciate your help

**Comment by nbrown02** [comment]
Sorry I said "boards in your project" - that's what I need to replicate your setup, not the screenshots for loading :) thanks

**Comment by priyankshah1410** [comment]
Not sure if I can Provide you the screenshot of boards within the project,
But below please find the details of columns from one of the sample board where column names are visible.
![image](https://user-images.githubusercontent.com/10057212/204395467-49724a73-aa52-4362-8cf2-26a19ccd14fb.png)
Let me know if that helps.

**Comment by nbrown02** [comment]
Thanks - I would need to know what the board design is for all teams within the ADO project, what columns states map to, as well as the area paths and what teams they are associated with.Without this it’s impossible to triage…Sent from my iPhoneOn 28 Nov 2022, at 22:37, priyankshah1410 ***@***.***> wrote:﻿
Not sure if I can Provide you the screenshot of boards within the project,
But below please find the details of columns from one of the sample board where column names are visible.

Let me know if that helps.

**Comment by priyankshah1410** [comment]
We currently have over 100 teams in our PROD project area, each with its own area path. All teams have the same Board structure with a column on the Board for each work item State. There may be some Scrum Masters who have done some customization where they have a State mapped to multiple columns but that is the exception.

Is it possible for us to have a meeting so that we can walk you through our screenshare?

**Comment by nbrown02** [comment]
Yeah that is probably best. If you drop me an email about your availability in the next couple weeks that would be great.Thanks,NickSent from my iPhoneOn 29 Nov 2022, at 16:29, priyankshah1410 ***@***.***> wrote:﻿
We currently have over 100 teams in our PROD project area, each with its own area path. All teams have the same Board structure with a column on the Board for each work item State. There may be some Scrum Masters who have done some customization where they have a State mapped to multiple columns but that is the exception.
Is it possible for us to have a meeting so that we can walk you through our screenshare?

**Comment by priyankshah1410** [comment]
Hello Nick,

Can you please send me your email, which doesn't reflect here, since we do not want our emails to go public.

**Comment by nbrown02** [comment]
If you scroll up on this issue it's in my reply :)

**Comment by priyankshah1410** [comment]
Perfect, sorry on missing out that
Sent you an email

**Comment by nbrown02** [comment]
Data being loaded is of such a significant size that the load is timing out and this cannot be fixed. Have provided user with two modified templates that can filter by [Team Name](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project)%20-%20Team%20Filter.pbit) or [Area Path](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project)%20-%20Area%20Path%20Filter.pbit).

**Comment by coachrye** [comment]
Hi @nbrown02 . Any chance those modified templates are still available? Thank you.

**Comment by nbrown02** [comment]
> Hi [@nbrown02](https://github.com/nbrown02) . Any chance those modified templates are still available? Thank you.

@coachrye try [this link](https://github.com/nbrown02/FlowViz/raw/refs/heads/main/Screenshots/FlowViz%20(Project%20-%20Team%20filter).pbit) :)

**Comment by coachrye** [comment]
> > Hi [@nbrown02](https://github.com/nbrown02) . Any chance those modified templates are still available? Thank you.
> 
> [@coachrye](https://github.com/coachrye) try [this link](https://github.com/nbrown02/FlowViz/raw/refs/heads/main/Screenshots/FlowViz%20(Project%20-%20Team%20filter).pbit) :)

Thank you so much for this. I was able to download and I'll give it a try tomorrow.
