### ISSUE TITLE
Error with Areas for projects 

### ISSUE THREAD

**Issue by avados** [nbrown02/FlowViz#90]
Hello,

Your project looks awesome, but when I am trying to load the data with the project pbit, i have an error : 
```
Areas
Column AreaSK in table Areas contains a duplicate value <UUID>  and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table

```
I am using power bi desktop, with an on premise Azure devops server 2020 update 1.1.

Am i doing something wrong?

Thanks

**Comment by nbrown02** [comment]
Hey Christophe,

Thanks for reaching out. This looks like a bug that has somehow been
introduced by Power BI messing with the relationships, let me fix it now
and commit a new version :)

**Comment by nbrown02** [comment]
Should now be fixed :)

**Comment by avados** [comment]
Are you for real? that was quick !
The refresh is still ongoing after 2 hours (very large project with a lot of teams) but i haven't got the error.

Thanks a lot !

**Comment by nbrown02** [comment]
Ha it's the support I like to provide!

If it's of use, there are templates I have that can filter by [Area Path ](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project)%20-%20Area%20Path%20Filter.pbit) or [Team.](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project)%20-%20Team%20Filter.pbit)..I just don't publicly advertise them!

**Comment by avados** [comment]
I will tell you how long it takes to refresh (3hours and counting). But the Area path template could help.
I will keep you updated.

Thanks again.

**Comment by nbrown02** [comment]
Yeah that’s a lot of work items in a project!! It’s difficult for me to test as I can’t generate those kind of volumes, hopefully those other templates can provide some help :) Sent from my iPhoneOn 10 Mar 2023, at 18:26, Christophe Lefrancois ***@***.***> wrote:﻿
I will tell you how long it takes to refresh (3hours and counting). But the Area path template could help.
I will keep you updated.
Thanks again.
