### ISSUE TITLE
Area Path reset if you tick Highlight blocked items checkbox

### ISSUE THREAD

**Issue by devyous** [nbrown02/FlowViz#91]
**Describe the bug**
First of all, many thanks for this fantastic project. I think I’ve found a small bug.

On the WiP tab/page if you select an Area Path and after that tick the checkbox Highlight blocked items, the Area Path drop-down gets reset.

I do want to mention that I don’t have any items with a blocked Tag, maybe that plays a role.

**Desktop:**
 - OS: Windows 11 64-bit
 - Browser Latest Edge
 - Version Latest PowerBI Desktop (language set to English US)

**Comment by nbrown02** [comment]
Thanks for raising this. Sounds like a bug I just need to check the impact of chart sorting if I try to fix this. Will update in the coming days :)

**Comment by nbrown02** [comment]
Hi there,

Unfortunately I won't be fixing this :( 

To get the slicers to retain I need to unselect the following:
![image](https://user-images.githubusercontent.com/29369962/225391885-18aecab0-aeed-46eb-9794-409c1859a6f1.png)

However when I do that, this happens:

![issue](https://user-images.githubusercontent.com/29369962/225392824-d1b434ba-8af3-4f2a-8e8f-a0afd6e309a7.gif)

Which is of course a much worse user experience!

Open for others to try of course...but not something I'm sure how to fix...
