### ISSUE TITLE
Unable to open template without power bi report server

### ISSUE THREAD

**Issue by mrweiland** [nbrown02/FlowViz#94]
**Describe the bug**
When open single project template i get 
![image](https://user-images.githubusercontent.com/12168854/225687413-ed3358e9-a784-46bf-b7ae-025e9f2f0ca7.png)

**To Reproduce**
Download single project and try to open it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 
![image](https://user-images.githubusercontent.com/12168854/225687675-8406129a-b656-4a26-af29-a16a995ce5c5.png)

**Comment by nbrown02** [comment]
Hi there,

I don't test against/or provide support for Power Bi Report Server I'm
afraid. Sorry about that :(

Thanks,

Nick
