### ISSUE TITLE
Wiki article "How much Work Item data is loaded?" out of date?

### ISSUE THREAD

**Issue by angelo-i** [nbrown02/FlowViz#95]
**Describe the bug**
In the Wiki, 7. FAQ, the article "How much Work Item data is loaded?" does not list WorkItems FlowEfficiency in the list of dataset that can have their dates adjusted.

**To Reproduce**
1. Go to [FlowViz Wiki, section 7., 1st article](https://github.com/nbrown02/FlowViz/wiki/7.-FAQs#how-much-work-item-data-is-loaded)
4. See wiki article to review (and update if necessary)

**Expected behavior**
Have an updated list of datasets that can have their dates edited, and the dataset recommended timeframe. At least for "WorkItems FlowEfficiency", but also any other relevant dataset not present in the list

**Screenshots**
n/r

**Desktop (please complete the following information):**
n/r

**Smartphone (please complete the following information):**
n/r

**Additional context**
n/r

**Comment by nbrown02** [comment]
This is now fixed :)
