### ISSUE TITLE
Forecast page freezes when trying to change input filters 

### ISSUE THREAD

**Issue by mwolak-abb** [nbrown02/FlowViz#99]
Hi! I'm using your template for 3 of my projects and recently I have a problem with forecasting tab. It freezes on any change of the filters input and at some point it crashes the browser tab. Can you help me investigate and fix the problem? I've got the same problem for each of 3 projects, each is in different organisation of ADO cloud version. 

**Describe the bug**
Forecast page freezes when trying to change input filters 

**To Reproduce**
1. Go to Forecast page on published web view (Desktop version has the same problem)
2. Click on Numbers of Weeks to forecast on What we will get? section and change it to any value
3. Actually any change on this page causes freeze (Change of input data range, team, etc) 
4. Loading indicator appear and the request behind is constantly pending an answer. No matter how long I wait, the re

**Expected behavior**
Refresh of the data. Maybe a timeout on the request can be added? 

**Screenshots**
![image](https://user-images.githubusercontent.com/131440813/233581850-9d0b2e3a-4ad6-4456-afbc-39cd43706a79.png)
![image](https://user-images.githubusercontent.com/131440813/233581920-4c29f234-9f90-469e-be05-76c0924dc26c.png)
![image](https://user-images.githubusercontent.com/131440813/233582807-037ef31c-2d63-4164-890c-9fdbab5fca9a.png)

**Request Payload**
`{"version":"1.0.0","queries":[{"Query":{"Commands":[{"SemanticQueryDataShapeCommand":{"Query":{"Version":2,"From":[{"Name":"n","Entity":"Number of weeks to forecast","Type":0},{"Name":"d","Entity":"Dates","Type":0},{"Name":"w","Entity":"WorkItems Completed","Type":0}],"Select":[{"Aggregation":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"Number of weeks"}},"Function":0},"Name":"Sum(Number of weeks to forecast.Number of weeks)"},{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"WeekStartingDate"},"Name":"Dates.WeekStartingDate"},{"Aggregation":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"CompletedDate"}},"Function":5},"Name":"WorkItems Completed.CompletedDate"}],"Where":[{"Condition":{"And":{"Left":{"Not":{"Expression":{"Comparison":{"ComparisonKind":0,"Left":{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"WorkItemType"}},"Right":{"Literal":{"Value":"'Epic'"}}}}}},"Right":{"Not":{"Expression":{"Comparison":{"ComparisonKind":0,"Left":{"Column":{"Expression":{"SourceRef":{"Source":"w"}},"Property":"WorkItemType"}},"Right":{"Literal":{"Value":"'Feature'"}}}}}}}}},{"Condition":{"Between":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"WeekStartingDate"}},"LowerBound":{"DateSpan":{"Expression":{"DateAdd":{"Expression":{"DateAdd":{"Expression":{"Now":{}},"Amount":1,"TimeUnit":0}},"Amount":-12,"TimeUnit":1}},"TimeUnit":0}},"UpperBound":{"DateSpan":{"Expression":{"Now":{}},"TimeUnit":0}}}}},{"Condition":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"Number of weeks"}}],"Values":[[{"Literal":{"Value":"12L"}}]]}}}]},"Binding":{"Primary":{"Groupings":[{"Projections":[1,2,0],"ShowItemsWithNoData":[1,2,0]}]},"DataReduction":{"DataVolume":3,"Primary":{"Top":{"Count":30000}}},"Version":1},"ExecutionMetricsKind":1}}]},"QueryId":"eb83661b-0562-98c6-f556-883910a9cc2c","ApplicationContext":{"DatasetId":"374ebe84-276c-4610-bcfc-d54acc9f38aa","Sources":[{"ReportId":"2cf06cd4-d6e4-4e80-8816-9260deb18343","VisualId":"ee79c1c253d569620372"}]}}],"cancelQueries":[],"modelId":16697922,"userPreferredLocale":"en-GB"}`

**Desktop (please complete the following information):**
 - OS: MacOs, Win
 - Browser: Chrome
 - Version 112.0.5615.49 (Official Build) (arm64)

**Comment by nbrown02** [comment]
Hi there - this is an issue that has just started to appear in the last few weeks. I have already logged as #98 - currently awaiting response from Microsoft and/or the visual creator...

Will close this issue as it's a duplicate :)

**Comment by mwolak-abb** [comment]
Sure, let me know if any input from my side can help you with pushing Microsoft. It might be a global issue from our perspective.

**Comment by mwolak-abb** [comment]
> @mwolak-abb - check the latest release - this is now fixed :)

Thanks for letting me know. I'm using mostly the cloud based PBI report based on your template. I assume that i should set it up once again based on fresh version? Or will it automagically fix itself on current cloud report? :)

**Comment by nbrown02** [comment]
Yeah unfortunately I never made it into an 'app' so download, reconnect to your source and overwrite the file then republish to power bi web service. The latest release does also have some cool new additions like the daily WIP chart showing WIP limit breaches :)
